-- Seed file with additional ingredients (Migration 2)
-- Run this after seed-ingredients.sql
-- Uses ON CONFLICT DO NOTHING to avoid duplicates
-- Total new ingredients: ~273

-- Asian Essentials
INSERT INTO ingredients (name, category, aliases) VALUES
('Silken Tofu', 'Produce', ARRAY['Silken tofu', 'Soft tofu']),
('Firm Tofu', 'Produce', ARRAY['Firm tofu']),
('Fried Tofu', 'Produce', ARRAY['Fried tofu', 'Agedashi tofu']),
('Udon', 'Grains', ARRAY['Udon noodles']),
('Soba', 'Grains', ARRAY['Soba noodles', 'Buckwheat noodles']),
('Ramen', 'Grains', ARRAY['Ramen noodles']),
('Somen', 'Grains', ARRAY['Somen noodles']),
('Shirataki', 'Grains', ARRAY['Shirataki noodles', 'Konjac noodles']),
('Nori', 'Produce', ARRAY['Nori sheets', 'Seaweed sheets']),
('Kombu', 'Produce', ARRAY['Kombu', 'Kelp']),
('Wakame', 'Produce', ARRAY['Wakame', 'Seaweed']),
('Hijiki', 'Produce', ARRAY['Hijiki', 'Hiziki']),
('Arame', 'Produce', ARRAY['Arame']),
('Dulse', 'Produce', ARRAY['Dulse']),
('Kelp Noodles', 'Produce', ARRAY['Kelp noodles']),
('Shiitake Mushroom', 'Produce', ARRAY['Dried shiitake', 'Shiitake']),
('Wood Ear', 'Produce', ARRAY['Wood ear mushroom', 'Cloud ear']),
('Enoki', 'Produce', ARRAY['Enoki mushrooms', 'Enoki']),
('Beech Mushroom', 'Produce', ARRAY['Beech mushroom', 'Shimeji']),
('King Oyster Mushroom', 'Produce', ARRAY['King oyster mushroom']),
('Rice Vinegar', 'Condiments', ARRAY['Rice vinegar']),
('Mirin', 'Condiments', ARRAY['Mirin']),
('Sake', 'Condiments', ARRAY['Cooking sake', 'Sake']),
('Dashi', 'Condiments', ARRAY['Dashi', 'Dashi powder']),
('Mentsuyu', 'Condiments', ARRAY['Mentsuyu', 'Noodle sauce']),
('Ponzu', 'Condiments', ARRAY['Ponzu']),
('Yuzu', 'Produce', ARRAY['Yuzu']),
('Yuzu Juice', 'Condiments', ARRAY['Yuzu juice']),
('Yuzu Kosho', 'Condiments', ARRAY['Yuzu kosho']),
('White Miso', 'Condiments', ARRAY['White miso', 'Shiro miso']),
('Red Miso', 'Condiments', ARRAY['Red miso', 'Aka miso']),
('Barley Miso', 'Condiments', ARRAY['Barley miso']),
('Gochujang', 'Condiments', ARRAY['Gochujang']),
('Doenjang', 'Condiments', ARRAY['Doenjang']),
('Ssamjang', 'Condiments', ARRAY['Ssamjang']),
('Kimchi', 'Produce', ARRAY['Kimchi', 'Fermented cabbage']),
('Tteok', 'Grains', ARRAY['Rice cakes', 'Tteok']),
('Dangmyeon', 'Grains', ARRAY['Glass noodles', 'Cellophane noodles']),
('Thai Basil', 'Produce', ARRAY['Thai basil']),
('Holy Basil', 'Produce', ARRAY['Holy basil', 'Thai holy basil']),
('Galangal', 'Produce', ARRAY['Galangal']),
('Kaffir Lime Leaf', 'Produce', ARRAY['Kaffir lime leaves', 'Lime leaf']),
('Pandan Leaf', 'Produce', ARRAY['Pandan leaf']),
('Tamarind Paste', 'Condiments', ARRAY['Tamarind paste']),
('Tamarind Concentrate', 'Condiments', ARRAY['Tamarind concentrate']),
('Sweet Soy Sauce', 'Condiments', ARRAY['Sweet soy sauce', 'Kecap manis']),
('Chili Oil', 'Condiments', ARRAY['Chili oil']),
('Chili Crisp', 'Condiments', ARRAY['Chili crisp', 'Chile crunch']),
('Sambal Oelek', 'Condiments', ARRAY['Sambal oelek']),
('Peanut Sauce', 'Condiments', ARRAY['Peanut sauce', 'Satay sauce']),
('Curry Paste', 'Condiments', ARRAY['Curry paste']),
('Green Curry Paste', 'Condiments', ARRAY['Green curry paste']),
('Red Curry Paste', 'Condiments', ARRAY['Red curry paste']),
('Yellow Curry Paste', 'Condiments', ARRAY['Yellow curry paste']),
('Massaman Curry Paste', 'Condiments', ARRAY['Massaman curry paste']),
('Panang Curry Paste', 'Condiments', ARRAY['Panang curry paste']),
('Laksa Paste', 'Condiments', ARRAY['Laksa paste']),
('Tom Yum Paste', 'Condiments', ARRAY['Tom yum paste'])
ON CONFLICT (name) DO NOTHING;

-- Indian/Pakistani Essentials
INSERT INTO ingredients (name, category, aliases) VALUES
('Toor Dal', 'Grains', ARRAY['Toor dal', 'Pigeon peas']),
('Urad Dal', 'Grains', ARRAY['Urad dal', 'Black gram']),
('Moong Dal', 'Grains', ARRAY['Moong dal', 'Mung beans']),
('Chana Dal', 'Grains', ARRAY['Chana dal', 'Split chickpeas']),
('Masoor Dal', 'Grains', ARRAY['Masoor dal', 'Red lentils']),
('Rajma', 'Grains', ARRAY['Rajma', 'Kidney beans']),
('Pav', 'Grains', ARRAY['Pav', 'Dinner rolls']),
('Paratha', 'Grains', ARRAY['Paratha', 'Flatbread']),
('Naan', 'Grains', ARRAY['Naan', 'Naan bread']),
('Roti', 'Grains', ARRAY['Roti', 'Chapati']),
('Puri', 'Grains', ARRAY['Puri', 'Puffed bread']),
('Amchur', 'Condiments', ARRAY['Amchur', 'Mango powder']),
('Anardana', 'Condiments', ARRAY['Anardana', 'Pomegranate seeds']),
('Asafoetida', 'Condiments', ARRAY['Asafoetida', 'Hing']),
('Curry Leaves', 'Produce', ARRAY['Curry leaves']),
('Kasuri Methi', 'Produce', ARRAY['Kasuri methi', 'Dried fenugreek']),
('Panch Phoron', 'Condiments', ARRAY['Panch phoron', 'Five spice']),
('Tandoori Masala', 'Condiments', ARRAY['Tandoori masala']),
('Chaat Masala', 'Condiments', ARRAY['Chaat masala']),
('Biryani Masala', 'Condiments', ARRAY['Biryani masala']),
('Sambar Powder', 'Condiments', ARRAY['Sambar powder']),
('Rasam Powder', 'Condiments', ARRAY['Rasam powder']),
('Kashmiri Chili', 'Condiments', ARRAY['Kashmiri chili']),
('Deghi Mirch', 'Condiments', ARRAY['Deghi mirch']),
('Turmeric Root', 'Produce', ARRAY['Fresh turmeric']),
('Ginger Garlic Paste', 'Condiments', ARRAY['Ginger garlic paste']),
('Green Chili', 'Produce', ARRAY['Green chili', 'Hari mirch']),
('Besan', 'Grains', ARRAY['Besan', 'Chickpea flour']),
('Sooji', 'Grains', ARRAY['Sooji', 'Semolina']),
('Idli Rice', 'Grains', ARRAY['Idli rice']),
('Idli', 'Grains', ARRAY['Idli', 'Idlis']),
('Dosa', 'Grains', ARRAY['Dosa', 'Dosas']),
('Appam', 'Grains', ARRAY['Appam']),
('Vada', 'Grains', ARRAY['Vada', 'Medu vada'])
ON CONFLICT (name) DO NOTHING;

-- Mexican/Latin Essentials
INSERT INTO ingredients (name, category, aliases) VALUES
('Masa', 'Grains', ARRAY['Masa', 'Masa harina']),
('Masa Dough', 'Grains', ARRAY['Masa dough']),
('Mexican Crema', 'Dairy', ARRAY['Mexican crema', 'Crema']),
('Chipotle', 'Produce', ARRAY['Chipotle']),
('Chipotles in Adobo', 'Condiments', ARRAY['Chipotles in adobo']),
('Ancho Chile', 'Produce', ARRAY['Ancho chile']),
('Guajillo', 'Produce', ARRAY['Guajillo']),
('Pasilla', 'Produce', ARRAY['Pasilla']),
('Mulato', 'Produce', ARRAY['Mulato']),
('Chile Negro', 'Produce', ARRAY['Chile negro']),
('Epazote', 'Produce', ARRAY['Epazote']),
('Nopalitos', 'Produce', ARRAY['Nopalitos', 'Cactus']),
('Mexican Oregano', 'Produce', ARRAY['Mexican oregano']),
('Cilantro Root', 'Produce', ARRAY['Cilantro root']),
('Corn Tortilla', 'Produce', ARRAY['Corn tortilla']),
('Flour Tortilla', 'Produce', ARRAY['Flour tortilla']),
('Taco Shells', 'Produce', ARRAY['Taco shells']),
('Salsa Verde', 'Condiments', ARRAY['Salsa verde', 'Green salsa']),
('Salsa Roja', 'Condiments', ARRAY['Salsa roja', 'Red salsa']),
('Pico de Gallo', 'Condiments', ARRAY['Pico de gallo']),
('Salsa Casera', 'Condiments', ARRAY['Salsa casera']),
('Taco Seasoning', 'Condiments', ARRAY['Taco seasoning']),
('Fajita Seasoning', 'Condiments', ARRAY['Fajita seasoning']),
('Cumin Seed', 'Produce', ARRAY['Cumin seeds']),
('Coriander Seed', 'Produce', ARRAY['Coriander seeds']),
('Mexican Chocolate', 'Baking', ARRAY['Mexican chocolate']),
('Atole', 'Grains', ARRAY['Atole']),
('Horchata', 'Beverages', ARRAY['Horchata']),
('Tamarind', 'Produce', ARRAY['Tamarind']),
('Piloncillo', 'Grains', ARRAY['Piloncillo']),
('Aguave', 'Grains', ARRAY['Aguave', 'Agave']),
('Ripe Plantain', 'Produce', ARRAY['Ripe plantain', 'Maduros']),
('Sweet Plantain', 'Produce', ARRAY['Sweet plantain']),
('Mexican Chorizo', 'Meat', ARRAY['Mexican chorizo']),
('Spanish Chorizo', 'Meat', ARRAY['Spanish chorizo']),
('Carnitas', 'Meat', ARRAY['Carnitas']),
('Carne Asada', 'Meat', ARRAY['Carne asada']),
('Carne Molida', 'Meat', ARRAY['Carne molida', 'Ground beef']),
('Pollo Asado', 'Meat', ARRAY['Pollo asado']),
('Shredded Chicken', 'Meat', ARRAY['Shredded chicken']),
('Refried Beans', 'Condiments', ARRAY['Refried beans']),
('Black Beans', 'Canned', ARRAY['Black beans']),
('Pinto Beans', 'Canned', ARRAY['Pinto beans']),
('Cannellini Beans', 'Canned', ARRAY['Cannellini beans']),
('Navy Beans', 'Canned', ARRAY['Navy beans']),
('Lima Beans', 'Canned', ARRAY['Lima beans']),
('Fava Beans', 'Canned', ARRAY['Fava beans'])
ON CONFLICT (name) DO NOTHING;

-- Middle Eastern / Mediterranean
INSERT INTO ingredients (name, category, aliases) VALUES
('Pomegranate Seeds', 'Produce', ARRAY['Pomegranate arils']),
('Freekeh', 'Grains', ARRAY['Freekeh']),
('Preserved Lemon', 'Produce', ARRAY['Preserved lemon']),
('Shawarma Spice', 'Condiments', ARRAY['Shawarma spice']),
('Piri Piri', 'Condiments', ARRAY['Piri piri']),
('Ground Lamb', 'Meat', ARRAY['Ground lamb']),
('Goat', 'Meat', ARRAY['Goat meat', 'Cabrito']),
('Halloumi', 'Dairy', ARRAY['Halloumi']),
('Pecorino Romano', 'Dairy', ARRAY['Pecorino']),
('Ricotta Salata', 'Dairy', ARRAY['Ricotta salata']),
('Marcona Almonds', 'Snacks', ARRAY['Marcona almonds']),
('Pine Nuts', 'Grains', ARRAY['Pine nuts']),
('Saffron Threads', 'Produce', ARRAY['Saffron threads']),
('Rose Water', 'Condiments', ARRAY['Rose water']),
('Orange Blossom Water', 'Condiments', ARRAY['Orange blossom water']),
('Orange Flower Water', 'Condiments', ARRAY['Orange flower water']),
('Elderflower', 'Produce', ARRAY['Elderflower']),
('Lavender', 'Produce', ARRAY['Lavender']),
('Capers', 'Produce', ARRAY['Capers']),
('Capers in brine', 'Produce', ARRAY['Capers in brine']),
('Anchovy Fillets', 'Seafood', ARRAY['Anchovy fillets']),
('Salted Anchovies', 'Seafood', ARRAY['Salted anchovies', 'Boquerones']),
('Olives', 'Produce', ARRAY['Olives']),
('Kalamata Olives', 'Produce', ARRAY['Kalamata olives']),
('Castelvetrano Olives', 'Produce', ARRAY['Castelvetrano olives']),
('Niçoise Olives', 'Produce', ARRAY['Niçoise olives']),
('Crushed Tomatoes', 'Canned', ARRAY['Crushed tomatoes']),
('Tomato Puree', 'Canned', ARRAY['Tomato puree']),
('Sun-Dried Tomatoes', 'Produce', ARRAY['Sun-dried tomatoes']),
('Fresh Basil', 'Produce', ARRAY['Basil']),
('Fresh Parsley', 'Produce', ARRAY['Parsley']),
('Fresh Cilantro', 'Produce', ARRAY['Cilantro']),
('Fresh Mint', 'Produce', ARRAY['Mint']),
('Fresh Rosemary', 'Produce', ARRAY['Rosemary']),
('Fresh Thyme', 'Produce', ARRAY['Thyme']),
('Fresh Oregano', 'Produce', ARRAY['Oregano']),
('Fresh Sage', 'Produce', ARRAY['Sage']),
('Fresh Dill', 'Produce', ARRAY['Dill']),
('Fresh Marjoram', 'Produce', ARRAY['Marjoram']),
('Fresh Tarragon', 'Produce', ARRAY['Tarragon']),
('Bay Leaves', 'Produce', ARRAY['Bay leaf'])
ON CONFLICT (name) DO NOTHING;

-- More Seafood
INSERT INTO ingredients (name, category, aliases) VALUES
('Smoked Mackerel', 'Seafood', ARRAY['Smoked mackerel']),
('Smoked Trout', 'Seafood', ARRAY['Smoked trout']),
('Kipper', 'Seafood', ARRAY['Kippers']),
('Bottarga', 'Seafood', ARRAY['Bottarga', 'Cured roe']),
('Roe', 'Seafood', ARRAY['Roe', 'Fish roe']),
('Ikura', 'Seafood', ARRAY['Ikura', 'Salmon roe']),
('Tobiko', 'Seafood', ARRAY['Tobiko', 'Flying fish roe']),
('Masago', 'Seafood', ARRAY['Masago', 'Capelin roe']),
('Crab Meat', 'Seafood', ARRAY['Crab meat']),
('Dungeness Crab', 'Seafood', ARRAY['Dungeness crab']),
('Blue Crab', 'Seafood', ARRAY['Blue crab']),
('King Crab', 'Seafood', ARRAY['King crab']),
('Snow Crab', 'Seafood', ARRAY['Snow crab']),
('Crab Legs', 'Seafood', ARRAY['Crab legs']),
('Lobster Tail', 'Seafood', ARRAY['Lobster tail']),
('Lobster Meat', 'Seafood', ARRAY['Lobster meat']),
('Tiger Shrimp', 'Seafood', ARRAY['Tiger shrimp']),
('Wild Shrimp', 'Seafood', ARRAY['Wild shrimp']),
('Bay Scallops', 'Seafood', ARRAY['Bay scallops']),
('Sea Scallops', 'Seafood', ARRAY['Sea scallops']),
('Mussels', 'Seafood', ARRAY['Mussels']),
('Clams', 'Seafood', ARRAY['Clams']),
('Little Neck Clams', 'Seafood', ARRAY['Little neck clams']),
('Manila Clams', 'Seafood', ARRAY['Manila clams']),
('Oysters', 'Seafood', ARRAY['Oysters']),
('Pacific Oysters', 'Seafood', ARRAY['Pacific oysters']),
('Kumamoto Oysters', 'Seafood', ARRAY['Kumamoto oysters']),
('Cuttlefish', 'Seafood', ARRAY['Cuttlefish']),
('Calamari', 'Seafood', ARRAY['Calamari', 'Squid']),
('Whole Squid', 'Seafood', ARRAY['Whole squid']),
('Baby Octopus', 'Seafood', ARRAY['Baby octopus']),
('Sea Urchin', 'Seafood', ARRAY['Sea urchin', 'Uni']),
('Conch', 'Seafood', ARRAY['Conch']),
('Fish Stock', 'Seafood', ARRAY['Fish stock']),
('Shrimp Stock', 'Seafood', ARRAY['Shrimp stock']),
('Lobster Stock', 'Seafood', ARRAY['Lobster stock']),
('Fumet', 'Seafood', ARRAY['Fumet'])
ON CONFLICT (name) DO NOTHING;

-- More Dairy & Eggs
INSERT INTO ingredients (name, category, aliases) VALUES
('Clotted Cream', 'Dairy', ARRAY['Clotted cream']),
('Crème Fraîche', 'Dairy', ARRAY['Creme fraiche']),
('Creme Fresh', 'Dairy', ARRAY['Creme fresh']),
('Cultured Buttermilk', 'Dairy', ARRAY['Cultured buttermilk']),
('Mascarpone', 'Dairy', ARRAY['Mascarpone']),
('Burrata', 'Dairy', ARRAY['Burrata']),
('Fresh Mozzarella', 'Dairy', ARRAY['Fresh mozzarella']),
('Buffalo Mozzarella', 'Dairy', ARRAY['Buffalo mozzarella']),
('Grana Padano', 'Dairy', ARRAY['Grana Padano']),
('Pecorino Toscano', 'Dairy', ARRAY['Pecorino Toscano']),
('Gorgonzola', 'Dairy', ARRAY['Gorgonzola']),
('Roquefort', 'Dairy', ARRAY['Roquefort']),
('Camembert', 'Dairy', ARRAY['Camembert']),
('Taleggio', 'Dairy', ARRAY['Taleggio']),
('Fontina', 'Dairy', ARRAY['Fontina']),
('Gruyere', 'Dairy', ARRAY['Gruyere']),
('Manchego', 'Dairy', ARRAY['Manchego']),
('Mahón', 'Dairy', ARRAY['Mahon']),
('Idiazabal', 'Dairy', ARRAY['Idiazabal']),
('Cabrales', 'Dairy', ARRAY['Cabrales']),
('Quail Egg', 'Dairy', ARRAY['Quail eggs']),
('Duck Egg', 'Dairy', ARRAY['Duck eggs']),
('Goose Egg', 'Dairy', ARRAY['Goose eggs']),
('Floyd Egg', 'Dairy', ARRAY['Floyd eggs']),
('Omega-3 Egg', 'Dairy', ARRAY['Omega-3 eggs']),
('Brown Egg', 'Dairy', ARRAY['Brown eggs']),
('Free-Range Egg', 'Dairy', ARRAY['Free-range eggs']),
('Organic Egg', 'Dairy', ARRAY['Organic eggs']),
('Whole Egg', 'Dairy', ARRAY['Whole eggs']),
('Whipping Cream', 'Dairy', ARRAY['Whipping cream']),
('Heavy Whipping Cream', 'Dairy', ARRAY['Heavy whipping cream']),
('Double Cream', 'Dairy', ARRAY['Double cream']),
('Skyr', 'Dairy', ARRAY['Skyr']),
('Coconut Cream', 'Canned', ARRAY['Coconut cream'])
ON CONFLICT (name) DO NOTHING;

-- More Grains & Rice
INSERT INTO ingredients (name, category, aliases) VALUES
('Carnaroli Rice', 'Grains', ARRAY['Carnaroli rice']),
('Vialone Nano Rice', 'Grains', ARRAY['Vialone nano']),
('Black Rice', 'Grains', ARRAY['Black rice', 'Forbidden rice']),
('Red Rice', 'Grains', ARRAY['Red Rice']),
('Wild Rice', 'Grains', ARRAY['Wild rice']),
('Sticky Rice', 'Grains', ARRAY['Sticky rice', 'Glutinous rice']),
('Paella Rice', 'Grains', ARRAY['Paella rice', 'Bomba']),
('Rice Paper', 'Grains', ARRAY['Rice paper']),
('Glass Noodles', 'Grains', ARRAY['Glass noodles']),
('Cellophane Noodles', 'Grains', ARRAY['Cellophane noodles']),
('Wheat Noodles', 'Grains', ARRAY['Wheat noodles']),
('Udon Noodles', 'Grains', ARRAY['Udon']),
('Soba Noodles', 'Grains', ARRAY['Soba']),
('Ramen Noodles', 'Grains', ARRAY['Ramen']),
('Somen Noodles', 'Grains', ARRAY['Somen']),
('Shirataki Noodles', 'Grains', ARRAY['Shirataki']),
('Spaetzle', 'Grains', ARRAY['Spaetzle']),
('Orzo', 'Grains', ARRAY['Orzo']),
('Israeli Couscous', 'Grains', ARRAY['Israeli couscous', 'Pearl couscous']),
('Pearl Couscous', 'Grains', ARRAY['Pearl couscous']),
('Fregola', 'Grains', ARRAY['Fregola']),
('Hulled Barley', 'Grains', ARRAY['Hulled barley']),
('White Quinoa', 'Grains', ARRAY['White quinoa']),
('Red Quinoa', 'Grains', ARRAY['Red quinoa']),
('Black Quinoa', 'Grains', ARRAY['Black quinoa']),
('Pearl Barley', 'Grains', ARRAY['Pearl barley']),
('All-Purpose Flour', 'Grains', ARRAY['Flour', 'AP flour']),
('Semolina', 'Grains', ARRAY['Semolina']),
('Cake Flour', 'Grains', ARRAY['Cake flour']),
('Pastry Flour', 'Grains', ARRAY['Pastry flour']),
('Gluten-Free Flour', 'Grains', ARRAY['Gluten-free flour']),
('Cornstarch', 'Grains', ARRAY['Cornstarch']),
('Xanthan Gum', 'Grains', ARRAY['Xanthan gum'])
ON CONFLICT (name) DO NOTHING;

-- Gourmet & Specialty Items
INSERT INTO ingredients (name, category, aliases) VALUES
('White Truffle Oil', 'Condiments', ARRAY['White truffle oil']),
('Black Truffle Oil', 'Condiments', ARRAY['Black truffle oil']),
('Truffle Paste', 'Condiments', ARRAY['Truffle paste']),
('Truffle Honey', 'Condiments', ARRAY['Truffle honey']),
('Vanilla Beans', 'Produce', ARRAY['Vanilla bean', 'Vanilla pods']),
('Vanilla Paste', 'Condiments', ARRAY['Vanilla paste']),
('Vanilla Powder', 'Condiments', ARRAY['Vanilla powder']),
('Saffron Powder', 'Condiments', ARRAY['Saffron powder']),
('Edible Gold Leaf', 'Baking', ARRAY['Gold leaf', 'Edible gold']),
('Edible Silver Leaf', 'Baking', ARRAY['Silver leaf', 'Edible silver']),
('Matcha Powder', 'Beverages', ARRAY['Matcha']),
('Ceremonial Grade Matcha', 'Beverages', ARRAY['Ceremonial matcha']),
('Culinary Matcha', 'Beverages', ARRAY['Culinary matcha']),
('Aged Balsamic', 'Condiments', ARRAY['Aged balsamic']),
('Balsamic Reduction', 'Condiments', ARRAY['Balsamic reduction']),
('Champagne Vinegar', 'Condiments', ARRAY['Champagne vinegar']),
('Sherry Vinegar', 'Condiments', ARRAY['Sherry vinegar']),
('Red Wine Vinegar', 'Condiments', ARRAY['Red wine vinegar']),
('White Wine Vinegar', 'Condiments', ARRAY['White wine vinegar']),
('Malt Vinegar', 'Condiments', ARRAY['Malt vinegar']),
('Demi-Glace', 'Condiments', ARRAY['Demi-glace', 'Demiglace']),
('Beef Fond', 'Condiments', ARRAY['Beef fond']),
('Chicken Fond', 'Condiments', ARRAY['Chicken fond']),
('Veal Stock', 'Condiments', ARRAY['Veal stock']),
('Duck Stock', 'Condiments', ARRAY['Duck stock']),
('Mushroom Stock', 'Condiments', ARRAY['Mushroom stock']),
('Vegetable Fond', 'Condiments', ARRAY['Vegetable fond']),
('Glace de Viande', 'Condiments', ARRAY['Glace de viande']),
('Compound Butter', 'Dairy', ARRAY['Compound butter']),
('Herb Butter', 'Dairy', ARRAY['Herb butter']),
('Garlic Butter', 'Dairy', ARRAY['Garlic butter']),
('Truffle Butter', 'Dairy', ARRAY['Truffle butter']),
('Goose Fat', 'Dairy', ARRAY['Goose fat']),
('Bacon Fat', 'Dairy', ARRAY['Bacon fat', 'Bacon grease']),
('Pork Rinds', 'Snacks', ARRAY['Pork rinds', 'Chicharrones']),
('Bread Crumbs', 'Grains', ARRAY['Breadcrumbs']),
('Panko', 'Grains', ARRAY['Panko breadcrumbs']),
('Italian Bread Crumbs', 'Grains', ARRAY['Italian breadcrumbs']),
('Seasoned Bread Crumbs', 'Grains', ARRAY['Seasoned breadcrumbs'])
ON CONFLICT (name) DO NOTHING;
