-- Seed ingredients 4: Additional ingredients for recipe generation
-- 400+ unique ingredients not in seed-ingredients.sql, seed-ingredients2.sql, or seed-ingredients3.sql
-- Run this in Supabase SQL Editor

INSERT INTO ingredients (name, category, aliases) VALUES
-- Proteins
('Chicken breast', 'Protein', ARRAY['Chicken', 'Boneless Chicken', 'Chicken Breast']),
('Chicken thighs', 'Protein', ARRAY['Chicken Thighs', 'Chicken Leg']),
('Chicken wings', 'Protein', ARRAY['Chicken Wings', 'Buffalo Wings']),
('Ground beef', 'Protein', ARRAY['Beef', 'Ground Beef', 'Minced Beef']),
('Beef steak', 'Protein', ARRAY['Steak', 'Beef Steak', 'Sirloin']),
('Beef tenderloin', 'Protein', ARRAY['Tenderloin', 'Filet']),
('Pork chops', 'Protein', ARRAY['Pork Chop', 'Pork Loin']),
('Pork belly', 'Protein', ARRAY['Pork Belly', 'Bacon Ends']),
('Ground pork', 'Protein', ARRAY['Ground Pork', 'Minced Pork']),
('Bacon', 'Protein', ARRAY['Bacon', 'Pork Bacon']),
('Ham', 'Protein', ARRAY['Ham', 'Smoked Ham']),
('Lamb chops', 'Protein', ARRAY['Lamb', 'Lamb Chops', 'Rack of Lamb']),
('Lamb leg', 'Protein', ARRAY['Lamb Leg']),
('Ground lamb', 'Protein', ARRAY['Ground Lamb', 'Minced Lamb']),
('Duck breast', 'Protein', ARRAY['Duck', 'Duck Breast']),
('Duck legs', 'Protein', ARRAY['Duck Legs']),
('Turkey breast', 'Protein', ARRAY['Turkey', 'Turkey Breast']),
('Ground turkey', 'Protein', ARRAY['Ground Turkey', 'Minced Turkey']),
('Venison', 'Protein', ARRAY['Deer', 'Venison', 'Wild Game']),
('Bison', 'Protein', ARRAY['Bison', 'Buffalo Meat']),
('Rabbit', 'Protein', ARRAY['Rabbit', 'Coney']),
('Goat meat', 'Protein', ARRAY['Goat', 'Goat Meat', 'Chevon']),
('Beef ribs', 'Protein', ARRAY['Beef Ribs', 'Short Ribs']),
('Pork ribs', 'Protein', ARRAY['Pork Ribs', 'Spare Ribs', 'Baby Back Ribs']),
('Beef brisket', 'Protein', ARRAY['Brisket']),
('Corned beef', 'Protein', ARRAY['Corned Beef']),
('Prosciutto', 'Protein', ARRAY['Prosciutto', 'Italian Ham']),
('Salami', 'Protein', ARRAY['Salami', 'Italian Sausage']),
('Chorizo', 'Protein', ARRAY['Chorizo', 'Spanish Sausage']),
('Italian sausage', 'Protein', ARRAY['Italian Sausage', 'Sweet Italian']),
('Bratwurst', 'Protein', ARRAY['Bratwurst', 'Brat']),
('Breakfast sausage', 'Protein', ARRAY['Breakfast Sausage', 'Pork Sausage']),
('Duck confit', 'Protein', ARRAY['Confit', 'Duck Confit']),
('Beef jerky', 'Protein', ARRAY['Jerky', 'Beef Jerky']),

-- Seafood
('Salmon fillet', 'Seafood', ARRAY['Salmon', 'Atlantic Salmon']),
('Salmon steak', 'Seafood', ARRAY['Salmon Steak']),
('Tuna steak', 'Seafood', ARRAY['Tuna', 'Ahi', 'Bluefin']),
('Tuna canned', 'Seafood', ARRAY['Canned Tuna', 'Tuna in Water']),
('Cod', 'Seafood', ARRAY['Cod', 'Pacific Cod', 'Atlantic Cod']),
('Halibut', 'Seafood', ARRAY['Halibut']),
('Tilapia', 'Seafood', ARRAY['Tilapia']),
('Trout', 'Seafood', ARRAY['Trout', 'Rainbow Trout']),
('Catfish', 'Seafood', ARRAY['Catfish']),
('Mahi mahi', 'Seafood', ARRAY['Mahi Mahi', 'Dolphinfish']),
('Swordfish', 'Seafood', ARRAY['Swordfish']),
('Sea bass', 'Seafood', ARRAY['Sea Bass', 'Branzino']),
('Red snapper', 'Seafood', ARRAY['Snapper', 'Red Snapper']),
('Mackerel', 'Seafood', ARRAY['Mackerel', 'Saba']),
('Sardines', 'Seafood', ARRAY['Sardines', 'Canned Sardines']),
('Anchovies', 'Seafood', ARRAY['Anchovy', 'Anchovies']),
('Herring', 'Seafood', ARRAY['Herring']),
('Clams', 'Seafood', ARRAY['Clam', 'Littleneck Clams']),
('Mussels', 'Seafood', ARRAY['Mussel', 'Blue Mussels']),
('Oysters', 'Seafood', ARRAY['Oyster', 'Pacific Oyster']),
('Scallops', 'Seafood', ARRAY['Scallop', 'Sea Scallop']),
('Shrimp', 'Seafood', ARRAY['Shrimp', 'Prawns']),
('Prawns', 'Seafood', ARRAY['Prawns', 'King Prawns']),
('Lobster', 'Seafood', ARRAY['Lobster', 'Maine Lobster']),
('Lobster tail', 'Seafood', ARRAY['Lobster Tail']),
('Crab meat', 'Seafood', ARRAY['Crab', 'Cock Crab', 'Dungeness']),
('Crab legs', 'Seafood', ARRAY['Crab Legs', 'King Crab']),
('Crawfish', 'Seafood', ARRAY['Crawfish', 'Crayfish']),
('Octopus', 'Seafood', ARRAY['Octopus']),
('Squid', 'Seafood', ARRAY['Squid', 'Calamari']),
('Calamari', 'Seafood', ARRAY['Calamari']),
('Seaweed', 'Seafood', ARRAY['Nori', 'Kelp', 'Kombu', 'Wakame']),
('Kelp', 'Seafood', ARRAY['Kelp']),
('Nori sheets', 'Seafood', ARRAY['Nori', 'Nori Sheets']),
('Fish stock', 'Seafood', ARRAY['Fish Stock', 'Fish Broth']),

-- Vegetables - Leafy Greens
('Romaine lettuce', 'Produce', ARRAY['Romaine', 'Cos Lettuce']),
('Iceberg lettuce', 'Produce', ARRAY['Iceberg', 'Cabbage Lettuce']),
('Butter lettuce', 'Produce', ARRAY['Butter Lettuce', 'Boston Lettuce']),
('Arugula', 'Produce', ARRAY['Arugula', 'Roquette']),
('Spinach', 'Produce', ARRAY['Spinach', 'Baby Spinach']),
('Kale', 'Produce', ARRAY['Kale', 'Lacinato Kale', 'Curly Kale']),
('Swiss chard', 'Produce', ARRAY['Chard', 'Swiss Chard']),
('Collard greens', 'Produce', ARRAY['Collards', 'Collard Greens']),
('Bok choy', 'Produce', ARRAY['Bok Choy', 'Pak Choi']),
('Napa cabbage', 'Produce', ARRAY['Napa Chinese Cabbage']),
('Cabbage', 'Produce', ARRAY['Cabbage', 'Green Cabbage']),
('Red cabbage', 'Produce', ARRAY['Red Cabbage', 'Purple Cabbage']),
('Brussels sprouts', 'Produce', ARRAY['Brussels Sprout']),
('Watercress', 'Produce', ARRAY['Watercress']),
('Endive', 'Produce', ARRAY['Endive', 'Belgian Endive']),
('Radicchio', 'Produce', ARRAY['Radicchio']),
('Frisee', 'Produce', ARRAY['Frisee', 'Curly Endive']),
('Mesclun', 'Produce', ARRAY['Mesclun', 'Mixed Greens']),
('Spring mix', 'Produce', ARRAY['Spring Mix', 'Baby Greens']),

-- Vegetables - Root & Tuber
('Sweet potato', 'Produce', ARRAY['Sweet Potato', 'Yam']),
('Russet potato', 'Produce', ARRAY['Russet Potato', 'Baking Potato']),
('Red potato', 'Produce', ARRAY['Red Potato', 'New Potato']),
('Fingerling potato', 'Produce', ARRAY['Fingerling']),
('Yukon gold', 'Produce', ARRAY['Yukon Gold', 'Yellow Potato']),
('Carrots', 'Produce', ARRAY['Carrot', 'Carrots']),
('Beets', 'Produce', ARRAY['Beet', 'Beetroot']),
('Turnips', 'Produce', ARRAY['Turnip']),
('Parsnips', 'Produce', ARRAY['Parsnip']),
('Rutabaga', 'Produce', ARRAY['Rutabaga', 'Swede']),
('Radishes', 'Produce', ARRAY['Radish', 'Daikon']),
('Daikon', 'Produce', ARRAY['Daikon', 'White Radish']),
('Ginger', 'Produce', ARRAY['Ginger', 'Fresh Ginger']),
('Turmeric root', 'Produce', ARRAY['Turmeric', 'Fresh Turmeric']),
('Horseradish', 'Produce', ARRAY['Horseradish']),
('Jicama', 'Produce', ARRAY['Jicama']),
('Celery root', 'Produce', ARRAY['Celeriac', 'Celery Root']),
('Water chestnuts', 'Produce', ARRAY['Water Chestnut']),
('Lotus root', 'Produce', ARRAY['Lotus Root']),

-- Vegetables - Nightshades
('Tomatoes', 'Produce', ARRAY['Tomato', 'Tomatoes']),
('Cherry tomatoes', 'Produce', ARRAY['Cherry Tomato', 'Grape Tomato']),
('Roma tomatoes', 'Produce', ARRAY['Roma', 'Plum Tomato']),
('Heirloom tomatoes', 'Produce', ARRAY['Heirloom']),
('Sun-dried tomatoes', 'Produce', ARRAY['Sun Dried Tomato']),
('Tomato paste', 'Pantry', ARRAY['Tomato Paste']),
('Tomato sauce', 'Pantry', ARRAY['Tomato Sauce', 'Marinara']),
('Tomato puree', 'Pantry', ARRAY['Tomato Puree']),
('Canned tomatoes', 'Pantry', ARRAY['Canned Tomato', 'Diced Tomatoes']),
('Bell peppers', 'Produce', ARRAY['Pepper', 'Bell Pepper', 'Peppers']),
('Red bell pepper', 'Produce', ARRAY['Red Pepper']),
('Green bell pepper', 'Produce', ARRAY['Green Pepper']),
('Yellow bell pepper', 'Produce', ARRAY['Yellow Pepper']),
('Orange bell pepper', 'Produce', ARRAY['Orange Pepper']),
('Poblano pepper', 'Produce', ARRAY['Poblano']),
('Jalapeno', 'Produce', ARRAY['Jalapeno', 'Jalapenos']),
('Serrano pepper', 'Produce', ARRAY['Serrano']),
('Habanero', 'Produce', ARRAY['Habanero', 'Scotch Bonnet']),
('Chipotle pepper', 'Pantry', ARRAY['Chipotle']),
('Anaheim pepper', 'Produce', ARRAY['Anaheim']),

-- Vegetables - Cruciferous
('Broccoli', 'Produce', ARRAY['Broccoli', 'Broccoli Florets']),
('Broccoli rabe', 'Produce', ARRAY['Rapini', 'Broccoli Rabe']),
('Cauliflower', 'Produce', ARRAY['Cauliflower']),
('Broccolini', 'Produce', ARRAY['Broccolini', 'Baby Broccoli']),

-- Vegetables - Squash & Gourd
('Zucchini', 'Produce', ARRAY['Zucchini', 'Courgette']),
('Yellow squash', 'Produce', ARRAY['Yellow Squash']),
('Butternut squash', 'Produce', ARRAY['Butternut']),
('Acorn squash', 'Produce', ARRAY['Acorn']),
('Spaghetti squash', 'Produce', ARRAY['Spaghetti']),
('Delicata squash', 'Produce', ARRAY['Delicata']),
('Kabocha', 'Produce', ARRAY['Kabocha', 'Japanese Pumpkin']),
('Pumpkin', 'Produce', ARRAY['Pumpkin']),
('Cucumber', 'Produce', ARRAY['Cucumber', 'English Cucumber']),
('English cucumber', 'Produce', ARRAY['English Cucumber', 'Hothouse']),
('Pickles', 'Pantry', ARRAY['Pickle', 'Dill Pickles']),
('Cornichons', 'Pantry', ARRAY['Cornichon', 'Gherkin']),

-- Vegetables - Alliums
('Yellow onion', 'Produce', ARRAY['Onion', 'Yellow Onion']),
('White onion', 'Produce', ARRAY['White Onion']),
('Red onion', 'Produce', ARRAY['Red Onion', 'Purple Onion']),
('Green onions', 'Produce', ARRAY['Green Onion', 'Scallion', 'Spring Onion']),
('Shallots', 'Produce', ARRAY['Shallot']),
('Leeks', 'Produce', ARRAY['Leek']),
('Chives', 'Produce', ARRAY['Chive']),

-- Vegetables - Herbs (Fresh)
('Basil fresh', 'Produce', ARRAY['Basil', 'Fresh Basil', 'Thai Basil']),
('Cilantro fresh', 'Produce', ARRAY['Cilantro', 'Coriander Leaves', 'Fresh Coriander']),
('Parsley fresh', 'Produce', ARRAY['Parsley', 'Fresh Parsley', 'Italian Parsley']),
('Mint fresh', 'Produce', ARRAY['Mint', 'Fresh Mint', 'Spearmint']),
('Rosemary fresh', 'Produce', ARRAY['Rosemary', 'Fresh Rosemary']),
('Thyme fresh', 'Produce', ARRAY['Thyme', 'Fresh Thyme']),
('Oregano fresh', 'Produce', ARRAY['Oregano', 'Fresh Oregano']),
('Sage fresh', 'Produce', ARRAY['Sage', 'Fresh Sage']),
('Dill fresh', 'Produce', ARRAY['Dill', 'Fresh Dill']),
('Tarragon fresh', 'Produce', ARRAY['Tarragon', 'Fresh Tarragon']),
('Marjoram fresh', 'Produce', ARRAY['Marjoram', 'Fresh Marjoram']),
('Bay leaves', 'Pantry', ARRAY['Bay Leaf', 'Laurel']),
('Lemongrass herb', 'Produce', ARRAY['Lemongrass']),
('Kaffir lime leaves', 'Produce', ARRAY['Kaffir Lime', 'Lime Leaves']),
('Curry leaves', 'Produce', ARRAY['Curry Leaf']),
('Culantro', 'Produce', ARRAY['Culantro', 'Recao']),

-- Vegetables - Other
('Corn', 'Produce', ARRAY['Corn', 'Sweet Corn', 'Kernel Corn']),
('Corn on the cob', 'Produce', ARRAY['Corn Cob']),
('Corn kernels', 'Produce', ARRAY['Corn Kernel']),
('Asparagus', 'Produce', ARRAY['Asparagus', 'Spears']),
('Artichoke', 'Produce', ARRAY['Artichoke', 'Artichoke Heart']),
('Artichoke hearts', 'Pantry', ARRAY['Artichoke Heart', 'Canned Artichoke']),
('Celery', 'Produce', ARRAY['Celery', 'Celery Stalk']),
('Fennel', 'Produce', ARRAY['Fennel', 'Fennel Bulb']),
('Mushrooms', 'Produce', ARRAY['Mushroom', 'Button Mushroom']),
('Cremini mushrooms', 'Produce', ARRAY['Cremini', 'Baby Bella']),
('Portobello mushrooms', 'Produce', ARRAY['Portobello', 'Portabella']),
('Shiitake mushrooms', 'Produce', ARRAY['Shiitake']),
('Oyster mushrooms', 'Produce', ARRAY['Oyster Mushroom']),
('Porcini mushrooms', 'Produce', ARRAY['Porcini']),
('Eggplant', 'Produce', ARRAY['Eggplant', 'Aubergine']),
('Okra', 'Produce', ARRAY['Okra']),
('Snow peas', 'Produce', ARRAY['Snow Pea', 'Mange Tout']),
('Sugar snap peas', 'Produce', ARRAY['Snap Pea', 'Sugar Snap']),
('Green beans', 'Produce', ARRAY['Green Bean', 'String Bean']),
('Peas vegetable', 'Produce', ARRAY['Pea', 'Green Pea']),
('Split peas', 'Pantry', ARRAY['Split Pea', 'Yellow Split Pea']),
('Black-eyed peas legume', 'Produce', ARRAY['Black Eyed Pea']),
('Bean sprouts', 'Produce', ARRAY['Bean Sprout', 'Mung Bean']),

-- Fruits
('Green apple', 'Produce', ARRAY['Granny Smith', 'Green Apple']),
('Orange fruit', 'Produce', ARRAY['Orange', 'Oranges', 'Navel Orange']),
('Lemon fruit', 'Produce', ARRAY['Lemon', 'Lemons']),
('Lime fruit', 'Produce', ARRAY['Lime', 'Limes']),
('Grapefruit', 'Produce', ARRAY['Grapefruit', 'Pink Grapefruit']),
('Pear fruit', 'Produce', ARRAY['Pear', 'Pears']),
('Peach fruit', 'Produce', ARRAY['Peach', 'Peaches']),
('Nectarine fruit', 'Produce', ARRAY['Nectarine', 'Nectarines']),
('Plum fruit', 'Produce', ARRAY['Plum', 'Plums']),
('Prunes fruit', 'Pantry', ARRAY['Prune', 'Dried Plum']),
('Mango fruit', 'Produce', ARRAY['Mango', 'Mangos']),
('Papaya fruit', 'Produce', ARRAY['Papaya']),
('Pineapple fruit', 'Produce', ARRAY['Pineapple']),
('Kiwi fruit', 'Produce', ARRAY['Kiwi', 'Kiwifruit']),
('Watermelon fruit', 'Produce', ARRAY['Watermelon']),
('Cantaloupe fruit', 'Produce', ARRAY['Cantaloupe', 'Rockmelon']),
('Honeydew fruit', 'Produce', ARRAY['Honeydew']),
('Grapes fruit', 'Produce', ARRAY['Grape', 'Grapes', 'Green Grape', 'Red Grape']),
('Strawberries fruit', 'Produce', ARRAY['Strawberry']),
('Blueberries fruit', 'Produce', ARRAY['Blueberry']),
('Raspberries fruit', 'Produce', ARRAY['Raspberry']),
('Blackberries fruit', 'Produce', ARRAY['Blackberry']),
('Cranberries fruit', 'Produce', ARRAY['Cranberry']),
('Cherries fruit', 'Produce', ARRAY['Cherry', 'Cherries']),
('Pomegranate fruit', 'Produce', ARRAY['Pomegranate']),
('Pomegranate seeds', 'Produce', ARRAY['Pomegranate Arils']),
('Fig fruit', 'Produce', ARRAY['Fig', 'Figs']),
('Dates fruit', 'Pantry', ARRAY['Date', 'Medjool']),
('Raisins fruit', 'Pantry', ARRAY['Raisin', 'Dried Raisin']),
('Dried apricots', 'Pantry', ARRAY['Dried Apricot', 'Apricot']),
('Dried mango fruit', 'Pantry', ARRAY['Dried Mango']),
('Coconut fruit', 'Produce', ARRAY['Coconut', 'Coconut Meat']),
('Coconut milk drink', 'Pantry', ARRAY['Coconut Milk', 'Coconut Cream']),
('Coconut cream fruit', 'Pantry', ARRAY['Coconut Cream']),
('Guava fruit', 'Produce', ARRAY['Guava']),
('Passion fruit', 'Produce', ARRAY['Passionfruit']),
('Dragon fruit', 'Produce', ARRAY['Dragonfruit']),
('Lychee fruit', 'Produce', ARRAY['Lychee', 'Litchi']),
('Star fruit', 'Produce', ARRAY['Starfruit', 'Carambola']),
('Persimmon fruit', 'Produce', ARRAY['Persimmon']),
('Apricot fruit', 'Produce', ARRAY['Apricot']),

-- Dairy
('2% milk dairy', 'Dairy', ARRAY['2 Percent Milk', 'Reduced Fat']),
('1% milk dairy', 'Dairy', ARRAY['1 Percent Milk', 'Low Fat']),
('Skim milk dairy', 'Dairy', ARRAY['Skim Milk', 'Nonfat']),
('Half and half dairy', 'Dairy', ARRAY['Half and Half', 'Half Half']),
('Heavy cream dairy', 'Dairy', ARRAY['Heavy Cream', 'Whipping Cream']),
('Light cream dairy', 'Dairy', ARRAY['Light Cream']),
('Evaporated milk dairy', 'Dairy', ARRAY['Evaporated Milk']),
('Condensed milk dairy', 'Dairy', ARRAY['Sweetened Condensed Milk']),
('Cream cheese dairy', 'Dairy', ARRAY['Cream Cheese']),
('Sour cream dairy', 'Dairy', ARRAY['Sour Cream']),
('Creme fraiche dairy', 'Dairy', ARRAY['Creme Fraiche']),
('Butter dairy', 'Dairy', ARRAY['Butter', 'Unsalted Butter', 'Salted Butter']),
('Clarified butter dairy', 'Dairy', ARRAY['Ghee', 'Clarified Butter']),
('Ghee dairy', 'Dairy', ARRAY['Ghee']),
('Yogurt dairy', 'Dairy', ARRAY['Yogurt', 'Greek Yogurt', 'Plain Yogurt']),
('Greek yogurt dairy', 'Dairy', ARRAY['Greek Yogurt']),
('Cottage cheese dairy', 'Dairy', ARRAY['Cottage Cheese']),
('Ricotta cheese dairy', 'Dairy', ARRAY['Ricotta']),
('Mascarpone dairy', 'Dairy', ARRAY['Mascarpone']),
('Mozzarella dairy', 'Dairy', ARRAY['Mozzarella', 'Fresh Mozzarella']),
('Fresh mozzarella dairy', 'Dairy', ARRAY['Fresh Mozzarella', 'Burrata']),
('Cheddar cheese dairy', 'Dairy', ARRAY['Cheddar']),
('Parmesan dairy', 'Dairy', ARRAY['Parmesan', 'Parmigiano', 'Parmigiano Reggiano']),
('Pecorino romano dairy', 'Dairy', ARRAY['Pecorino', 'Pecorino Romano']),
('Gruyere dairy', 'Dairy', ARRAY['Gruyere']),
('Swiss cheese dairy', 'Dairy', ARRAY['Swiss', 'Emmental']),
('Provolone dairy', 'Dairy', ARRAY['Provolone']),
('Feta cheese dairy', 'Dairy', ARRAY['Feta']),
('Goat cheese dairy', 'Dairy', ARRAY['Goat Cheese', 'Chevre']),
('Blue cheese dairy', 'Dairy', ARRAY['Blue Cheese', 'Gorgonzola']),
('Brie dairy', 'Dairy', ARRAY['Brie']),
('Camembert dairy', 'Dairy', ARRAY['Camembert']),

-- Grains & Starches
('Jasmine rice grain', 'Grains', ARRAY['Jasmine']),
('Basmati rice grain', 'Grains', ARRAY['Basmati']),
('Brown rice grain', 'Grains', ARRAY['Brown Rice']),
('Wild rice grain', 'Grains', ARRAY['Wild Rice']),
('Arborio rice grain', 'Grains', ARRAY['Arborio', 'Risotto Rice']),
('Sushi rice grain', 'Grains', ARRAY['Sushi Rice', 'Short Grain']),
('Black rice grain', 'Grains', ARRAY['Forbidden Rice']),
('Red rice grain', 'Grains', ARRAY['Red Rice']),
('Quinoa grain', 'Grains', ARRAY['Quinoa']),
('Couscous grain', 'Grains', ARRAY['Couscous']),
('Bulgur grain', 'Grains', ARRAY['Bulgur', 'Bulghur', 'Cracked Wheat']),
('Farro grain', 'Grains', ARRAY['Farro']),
('Barley grain', 'Grains', ARRAY['Barley', 'Pearl Barley']),
('Freekeh grain', 'Grains', ARRAY['Freekeh']),
('Millet grain', 'Grains', ARRAY['Millet']),
('Buckwheat grain', 'Grains', ARRAY['Buckwheat', 'Kasha']),
('Polenta grain', 'Grains', ARRAY['Polenta', 'Cornmeal']),
('Cornmeal grain', 'Grains', ARRAY['Cornmeal', 'Masa']),
('Cornstarch grain', 'Pantry', ARRAY['Cornstarch', 'Corn Starch']),
('Bread crumbs grain', 'Pantry', ARRAY['Breadcrumb', 'Panko']),
('Panko grain', 'Pantry', ARRAY['Panko', 'Japanese Breadcrumb']),
('Croutons grain', 'Pantry', ARRAY['Crouton']),
('Rolled oats grain', 'Grains', ARRAY['Oatmeal', 'Rolled Oat']),
('Steel cut oats grain', 'Grains', ARRAY['Steel Cut Oat', 'Irish Oat']),
('Oat flour grain', 'Grains', ARRAY['Oat Flour']),
('Rice flour grain', 'Grains', ARRAY['Rice Flour']),
('Coconut flour grain', 'Grains', ARRAY['Coconut Flour']),
('Tapioca flour grain', 'Grains', ARRAY['Tapioca', 'Tapioca Starch']),
('Bread flour grain', 'Grains', ARRAY['Bread Flour']),
('Semolina grain', 'Grains', ARRAY['Semolina']),
('Penne grain', 'Grains', ARRAY['Penne']),
('Fettuccine grain', 'Grains', ARRAY['Fettuccine']),
('Linguine grain', 'Grains', ARRAY['Linguine']),
('Rigatoni grain', 'Grains', ARRAY['Rigatoni']),
('Fusilli grain', 'Grains', ARRAY['Fusilli']),
('Farfalle grain', 'Grains', ARRAY['Farfalle', 'Bow Tie']),
('Orzo grain', 'Grains', ARRAY['Orzo']),
('Egg noodles grain', 'Grains', ARRAY['Egg Noodle']),
('Rice noodles grain', 'Grains', ARRAY['Rice Noodle', 'Vermicelli']),
('Udon grain', 'Grains', ARRAY['Udon']),
('Soba noodles grain', 'Grains', ARRAY['Soba', 'Buckwheat Noodle']),
('Glass noodles grain', 'Grains', ARRAY['Cellophane Noodle', 'Bean Thread']),
('Lasagna sheets grain', 'Grains', ARRAY['Lasagna', 'Noodle']),

-- Legumes
('Black beans legume', 'Legumes', ARRAY['Black Bean']),
('Kidney beans legume', 'Legumes', ARRAY['Kidney Bean']),
('Pinto beans legume', 'Legumes', ARRAY['Pinto Bean']),
('Navy beans legume', 'Legumes', ARRAY['Navy Bean', 'White Bean']),
('Cannellini beans legume', 'Legumes', ARRAY['Cannellini', 'White Kidney Bean']),
('Great northern beans', 'Legumes', ARRAY['Great Northern']),
('Chickpeas legume', 'Legumes', ARRAY['Chickpea', 'Garbanzo', 'Garbanzo Bean']),
('Hummus legume', 'Pantry', ARRAY['Hummus']),
('Lentils legume', 'Legumes', ARRAY['Lentil']),
('Green lentils legume', 'Legumes', ARRAY['Green Lentil']),
('Red lentils legume', 'Legumes', ARRAY['Red Lentil']),
('Lima beans legume', 'Legumes', ARRAY['Lima Bean', 'Butter Bean']),
('Mung beans legume', 'Legumes', ARRAY['Mung Bean', 'Moong']),
('Adzuki beans legume', 'Legumes', ARRAY['Adzuki', 'Red Bean']),
('Fava beans legume', 'Legumes', ARRAY['Fava Bean', 'Broad Bean']),
('Soybeans legume', 'Legumes', ARRAY['Soybean', 'Edamame']),
('Edamame legume', 'Legumes', ARRAY['Edamame']),
('Tofu legume', 'Protein', ARRAY['Tofu', 'Firm Tofu']),
('Silken tofu legume', 'Protein', ARRAY['Silken Tofu']),
('Tempeh legume', 'Protein', ARRAY['Tempeh']),
('Soy sauce legume', 'Pantry', ARRAY['Soy Sauce', 'Shoyu']),
('Tamari legume', 'Pantry', ARRAY['Tamari']),
('Miso paste legume', 'Pantry', ARRAY['Miso', 'White Miso']),
('Hoisin sauce legume', 'Pantry', ARRAY['Hoisin']),
('Tahini legume', 'Pantry', ARRAY['Tahini', 'Sesame Paste']),

-- Nuts & Seeds
('Walnuts nut', 'Nuts', ARRAY['Walnut']),
('Pecans nut', 'Nuts', ARRAY['Pecan']),
('Cashews nut', 'Nuts', ARRAY['Cashew']),
('Peanuts nut', 'Nuts', ARRAY['Peanut']),
('Peanut butter nut', 'Pantry', ARRAY['Peanut Butter']),
('Pistachios nut', 'Nuts', ARRAY['Pistachio']),
('Macadamia nuts nut', 'Nuts', ARRAY['Macadamia']),
('Hazelnuts nut', 'Nuts', ARRAY['Hazelnut', 'Filbert']),
('Brazil nuts nut', 'Nuts', ARRAY['Brazil Nut']),
('Pine nuts nut', 'Nuts', ARRAY['Pine Nut', 'Pignoli']),
('Sunflower seeds nut', 'Nuts', ARRAY['Sunflower Seed']),
('Pumpkin seeds nut', 'Nuts', ARRAY['Pepitas', 'Pumpkin Seed']),
('Sesame seeds nut', 'Nuts', ARRAY['Sesame Seed', 'Sesame']),
('Chia seeds nut', 'Nuts', ARRAY['Chia']),
('Flax seeds nut', 'Nuts', ARRAY['Flax', 'Flaxseed']),
('Hemp seeds nut', 'Nuts', ARRAY['Hemp', 'Hempy']),
('Poppy seeds nut', 'Nuts', ARRAY['Poppy Seed']),
('Almond butter nut', 'Pantry', ARRAY['Almond Butter']),

-- Oils & Fats
('Vegetable oil fat', 'Pantry', ARRAY['Vegetable Oil', 'Canola Oil']),
('Canola oil fat', 'Pantry', ARRAY['Canola']),
('Coconut oil fat', 'Pantry', ARRAY['Coconut Oil']),
('Sesame oil fat', 'Pantry', ARRAY['Sesame Oil', 'Toasted Sesame Oil']),
('Peanut oil fat', 'Pantry', ARRAY['Peanut Oil', 'Groundnut Oil']),
('Avocado oil fat', 'Pantry', ARRAY['Avocado Oil']),
('Walnut oil fat', 'Pantry', ARRAY['Walnut Oil']),
('Grapeseed oil fat', 'Pantry', ARRAY['Grapeseed']),
('Sunflower oil fat', 'Pantry', ARRAY['Sunflower Oil']),
('Lard fat', 'Pantry', ARRAY['Lard', 'Pork Fat']),
('Duck fat oil', 'Pantry', ARRAY['Duck Fat']),
('Beef tallow fat', 'Pantry', ARRAY['Tallow']),

-- Condiments & Sauces
('Ketchup condiment', 'Pantry', ARRAY['Ketchup', 'Catsup']),
('Mustard condiment', 'Pantry', ARRAY['Mustard', 'Dijon Mustard']),
('Dijon mustard condiment', 'Pantry', ARRAY['Dijon']),
('Whole grain mustard condiment', 'Pantry', ARRAY['Grain Mustard']),
('Mayonnaise condiment', 'Pantry', ARRAY['Mayo', 'Mayonnaise']),
('Hot sauce condiment', 'Pantry', ARRAY['Hot Sauce', 'Tabasco']),
('Sriracha condiment', 'Pantry', ARRAY['Sriracha']),
('Worcestershire sauce cond', 'Pantry', ARRAY['Worcestershire']),
('Soy sauce cond', 'Pantry', ARRAY['Soy Sauce']),
('Fish sauce cond', 'Pantry', ARRAY['Fish Sauce']),
('Oyster sauce cond', 'Pantry', ARRAY['Oyster Sauce']),
('Teriyaki sauce cond', 'Pantry', ARRAY['Teriyaki']),
('BBQ sauce cond', 'Pantry', ARRAY['Barbecue Sauce', 'BBQ Sauce']),
('Ranch dressing cond', 'Pantry', ARRAY['Ranch']),
('Italian dressing cond', 'Pantry', ARRAY['Italian Dressing']),
('Balsamic vinegar cond', 'Pantry', ARRAY['Balsamic']),
('Red wine vinegar cond', 'Pantry', ARRAY['Red Wine Vinegar']),
('White wine vinegar cond', 'Pantry', ARRAY['White Wine Vinegar']),
('Apple cider vinegar cond', 'Pantry', ARRAY['Apple Cider Vinegar']),
('Rice vinegar cond', 'Pantry', ARRAY['Rice Vinegar', 'Rice Wine']),
('Sherry vinegar cond', 'Pantry', ARRAY['Sherry Vinegar']),
('Champagne vinegar cond', 'Pantry', ARRAY['Champagne Vinegar']),
('Malt vinegar cond', 'Pantry', ARRAY['Malt Vinegar']),
('Salsa cond', 'Pantry', ARRAY['Salsa', 'Salsa Verde']),
('Salsa verde cond', 'Pantry', ARRAY['Salsa Verde', 'Tomatillo Salsa']),
('Guacamole cond', 'Pantry', ARRAY['Guacamole']),
('Pesto cond', 'Pantry', ARRAY['Pesto', 'Basil Pesto']),
('Tapenade cond', 'Pantry', ARRAY['Tapenade']),

-- Sweeteners & Baking
('Brown sugar sweetener', 'Pantry', ARRAY['Brown Sugar', 'Light Brown Sugar']),
('Dark brown sugar sweet', 'Pantry', ARRAY['Dark Brown Sugar']),
('Powdered sugar sweet', 'Pantry', ARRAY['Confectioners Sugar', 'Icing Sugar']),
('Honey sweetener', 'Pantry', ARRAY['Honey', 'Raw Honey']),
('Maple syrup sweet', 'Pantry', ARRAY['Maple Syrup', 'Pure Maple Syrup']),
('Molasses sweet', 'Pantry', ARRAY['Molasses', 'Blackstrap']),
('Corn syrup sweet', 'Pantry', ARRAY['Corn Syrup']),
('Rice syrup sweet', 'Pantry', ARRAY['Rice Syrup', 'Brown Rice Syrup']),
('Date syrup sweet', 'Pantry', ARRAY['Date Syrup']),
('Stevia sweetener', 'Pantry', ARRAY['Stevia']),
('Monk fruit sweetener', 'Pantry', ARRAY['Monk Fruit', 'Luo Han Guo']),
('Vanilla extract sweet', 'Pantry', ARRAY['Vanilla', 'Vanilla Extract']),
('Vanilla bean sweet', 'Pantry', ARRAY['Vanilla Bean']),
('Baking powder sweet', 'Pantry', ARRAY['Baking Powder']),
('Baking soda sweet', 'Pantry', ARRAY['Bicarbonate of Soda', 'Baking Soda']),
('Yeast sweet', 'Pantry', ARRAY['Yeast', 'Instant Yeast', 'Active Dry Yeast']),
('Gelatin sweet', 'Pantry', ARRAY['Gelatin']),
('Agar agar sweet', 'Pantry', ARRAY['Agar']),
('Cream of tartar sweet', 'Pantry', ARRAY['Cream of Tartar']),

-- Spices & Seasonings
('Salt spice', 'Pantry', ARRAY['Salt', 'Table Salt', 'Sea Salt', 'Kosher Salt']),
('Black pepper spice', 'Pantry', ARRAY['Pepper', 'Black Pepper', 'Ground Pepper']),
('White pepper spice', 'Pantry', ARRAY['White Pepper']),
('Cayenne pepper spice', 'Pantry', ARRAY['Cayenne']),
('Paprika spice', 'Pantry', ARRAY['Paprika', 'Smoked Paprika', 'Hungarian Paprika']),
('Smoked paprika spice', 'Pantry', ARRAY['Smoked Paprika', 'Pimenton']),
('Cumin spice', 'Pantry', ARRAY['Cumin', 'Ground Cumin']),
('Coriander spice', 'Pantry', ARRAY['Coriander', 'Ground Coriander']),
('Turmeric spice', 'Pantry', ARRAY['Turmeric', 'Ground Turmeric']),
('Cinnamon spice', 'Pantry', ARRAY['Cinnamon', 'Ground Cinnamon']),
('Nutmeg spice', 'Pantry', ARRAY['Nutmeg', 'Ground Nutmeg']),
('Cloves spice', 'Pantry', ARRAY['Clove', 'Ground Cloves']),
('Cardamom spice', 'Pantry', ARRAY['Cardamom', 'Ground Cardamom']),
('Ginger powder spice', 'Pantry', ARRAY['Ginger', 'Ground Ginger']),
('Garlic powder spice', 'Pantry', ARRAY['Garlic Powder']),
('Onion powder spice', 'Pantry', ARRAY['Onion Powder']),
('Chili powder spice', 'Pantry', ARRAY['Chili Powder']),
('Curry powder spice', 'Pantry', ARRAY['Curry Powder']),
('Garam masala spice', 'Pantry', ARRAY['Garam Masala']),
('Cajun seasoning spice', 'Pantry', ARRAY['Cajun']),
('Italian seasoning spice', 'Pantry', ARRAY['Italian Seasoning']),
('Five spice blend', 'Pantry', ARRAY['Chinese Five Spice', 'Five Spice']),
('Everything bagel seasoning', 'Pantry', ARRAY['Everything Bagel']),
('Taco seasoning spice', 'Pantry', ARRAY['Taco Seasoning']),
('Fajita seasoning spice', 'Pantry', ARRAY['Fajita']),
('Creole seasoning spice', 'Pantry', ARRAY['Creole', 'Cajun']),
('Zaatar spice', 'Pantry', ARRAY['Zaatar', 'Zaatar']),
('Sumac spice', 'Pantry', ARRAY['Sumac']),

-- International
('Mirin', 'Pantry', ARRAY['Mirin', 'Japanese Sweet Wine']),
('Sake', 'Pantry', ARRAY['Sake', 'Japanese Rice Wine']),
('Rice wine', 'Pantry', ARRAY['Rice Wine', 'Shaoxing']),
('Shaoxing wine', 'Pantry', ARRAY['Shaoxing']),
('Gochujang', 'Pantry', ARRAY['Gochujang', 'Korean Chili Paste']),
('Doenjang', 'Pantry', ARRAY['Doenjang', 'Korean Soybean Paste']),
('Doubanjiang', 'Pantry', ARRAY['Doubanjiang', 'Chili Bean Paste']),
('Sichuan peppercorn', 'Pantry', ARRAY['Sichuan Pepper', 'Flower Pepper']),
('Star anise', 'Pantry', ARRAY['Star Anise']),
('Galangal', 'Pantry', ARRAY['Galangal']),
('Palm sugar', 'Pantry', ARRAY['Palm Sugar', 'Jaggery']),
('Pomegranate molasses', 'Pantry', ARRAY['Pomegranate Molasses']);
