-- Seed ingredients: Latin American ingredients
-- 100 unique Latin American ingredients for recipe generation
-- Run this in Supabase SQL Editor

INSERT INTO ingredients (name, category, aliases) VALUES
-- Proteins
('Pollo', 'Protein', ARRAY['Chicken', 'Chicken Breast', 'Chicken Thighs']),
('Carne de res', 'Protein', ARRAY['Beef', 'Ground Beef', 'Beef Steak']),
('Carne de cerdo', 'Protein', ARRAY['Pork', 'Pork Chops', 'Pork Belly']),
('Carne molida', 'Protein', ARRAY['Ground Meat', 'Minced Meat']),
('Bistec', 'Protein', ARRAY['Steak', 'Beef Steak', 'Sirloin']),
('Costillas', 'Protein', ARRAY['Ribs', 'Short Ribs', 'Pork Ribs']),
('Chicharron', 'Protein', ARRAY['Pork Rinds', 'Crispy Pork']),
('Jamón', 'Protein', ARRAY['Ham', 'Serrano Ham']),
('Tocino', 'Protein', ARRAY['Bacon', 'Pork Bacon']),
('Chorizo español', 'Protein', ARRAY['Chorizo', 'Spanish Sausage']),
('Longaniza', 'Protein', ARRAY['Longaniza', 'Latin Sausage']),
('Salchicha', 'Protein', ARRAY['Hot Dog', 'Frankfurter', 'Sausage']),

-- Seafood
('Pescado', 'Seafood', ARRAY['Fish', 'White Fish', 'Fresh Fish']),
('Tilapia', 'Seafood', ARRAY['Tilapia', 'Mero']),
('Salmón', 'Seafood', ARRAY['Salmon']),
('Atún', 'Seafood', ARRAY['Tuna', 'Tuna Steak']),
('Camaron', 'Seafood', ARRAY['Shrimp', 'Prawns', 'Large Shrimp']),
('Langosta', 'Seafood', ARRAY['Lobster']),
('Camarones', 'Seafood', ARRAY['Shrimp', 'Small Shrimp']),
('Jaiba', 'Seafood', ARRAY['Crab', 'Crab Meat']),
('Almejas', 'Seafood', ARRAY['Clams']),
('Mejillas', 'Seafood', ARRAY['Mussels']),
('Ostras', 'Seafood', ARRAY['Oysters']),
('Bacalao', 'Seafood', ARRAY['Cod', 'Salt Cod', 'Dried Cod']),
('Aguachile', 'Seafood', ARRAY['Shrimp Ceviche', 'Raw Shrimp']),
('Ceviche', 'Seafood', ARRAY['Ceviche', 'Marinated Fish']),

-- Vegetables
('Tomate', 'Produce', ARRAY['Tomato', 'Tomatoes', 'Roma Tomato']),
('Tomate cherry', 'Produce', ARRAY['Cherry Tomato', 'Grape Tomato']),
('Jitomate', 'Produce', ARRAY['Tomato', 'Red Tomato']),
('Cebolla', 'Produce', ARRAY['Onion', 'Yellow Onion', 'White Onion']),
('Cebolla morada', 'Produce', ARRAY['Red Onion', 'Purple Onion']),
('Cebolleta', 'Produce', ARRAY['Green Onion', 'Scallion', 'Spring Onion']),
('Ajo', 'Produce', ARRAY['Garlic', 'Garlic Cloves']),
('Pimiento', 'Produce', ARRAY['Bell Pepper', 'Pepper']),
('Pimiento rojo', 'Produce', ARRAY['Red Bell Pepper']),
('Pimiento verde', 'Produce', ARRAY['Green Bell Pepper']),
('Chile', 'Produce', ARRAY['Chili', 'Chili Pepper']),
('Chile jalapeño', 'Produce', ARRAY['Jalapeno', 'Jalapenos']),
('Chile serrano', 'Produce', ARRAY['Serrano Pepper']),
('Chile poblano', 'Produce', ARRAY['Poblano', 'Poblano Pepper']),
('Chile habanero', 'Produce', ARRAY['Habanero', 'Scotch Bonnet']),
('Chile chipotle', 'Produce', ARRAY['Chipotle', 'Smoked Jalapeno']),
('Chile de árbol', 'Produce', ARRAY['Bird Pepper', 'Thai Chili']),
('Aguacate', 'Produce', ARRAY['Avocado', 'Aguacate']),
('Palta', 'Produce', ARRAY['Avocado']),
('Platano', 'Produce', ARRAY['Plantain']),
('Platano macho', 'Produce', ARRAY['Cooking Plantain']),
('Yuca', 'Produce', ARRAY['Cassava', 'Manioc']),
('Papa', 'Produce', ARRAY['Potato', 'White Potato', 'Russet Potato']),
('Camote', 'Produce', ARRAY['Sweet Potato', 'Yam']),
('Ejote', 'Produce', ARRAY['Green Bean', 'String Bean']),
('Elote', 'Produce', ARRAY['Corn', 'Sweet Corn', 'Corn on the Cob']),
('Maíz', 'Produce', ARRAY['Corn', 'Corn Kernels']),
('Chayote', 'Produce', ARRAY['Chayote', 'Vegetable Pear']),
('Nopal', 'Produce', ARRAY['Cactus', 'Cactus Pad', 'Nopales']),
('Verdura', 'Produce', ARRAY['Vegetable', 'Greens']),
('Lechuga', 'Produce', ARRAY['Lettuce', 'Romaine', 'Iceberg']),
('Espinaca', 'Produce', ARRAY['Spinach']),
('Acelga', 'Produce', ARRAY['Swiss Chard', 'Chard']),
('Col', 'Produce', ARRAY['Cabbage']),
('Coliflor', 'Produce', ARRAY['Cauliflower']),
('Brócoli', 'Produce', ARRAY['Broccoli']),
('Zanahoria', 'Produce', ARRAY['Carrot', 'Carrots']),
('Apio', 'Produce', ARRAY['Celery']),
('Pepino', 'Produce', ARRAY['Cucumber']),
('Rábano', 'Produce', ARRAY['Radish']),
('Betabel', 'Produce', ARRAY['Beet', 'Beetroot']),
('Calabaza', 'Produce', ARRAY['Squash', 'Pumpkin']),
('Calabacín', 'Produce', ARRAY['Zucchini', 'Courgette']),
('Chícharo', 'Produce', ARRAY['Peas', 'Green Peas']),
('Frijol negro', 'Legumes', ARRAY['Black Beans']),
('Frijol pinto', 'Legumes', ARRAY['Pinto Beans']),
('Frijol refrito', 'Legumes', ARRAY['Refried Beans']),
('Frijoles', 'Legumes', ARRAY['Beans', 'Kidney Beans']),
('Lentejas', 'Legumes', ARRAY['Lentils']),
('Garbanzo', 'Legumes', ARRAY['Chickpeas', 'Garbanzo Beans']),
('Habas', 'Legumes', ARRAY['Fava Beans', 'Broad Beans']),

-- Fruits
('Mango', 'Produce', ARRAY['Mango', 'Mangos']),
('Papaya', 'Produce', ARRAY['Papaya']),
('Piña', 'Produce', ARRAY['Pineapple']),
('Banano', 'Produce', ARRAY['Banana']),
('Guayaba', 'Produce', ARRAY['Guava']),
('Maracuyá', 'Produce', ARRAY['Passion Fruit']),
('Granadilla', 'Produce', ARRAY['Passion Fruit', 'Sweet Granadilla']),
('Limon', 'Produce', ARRAY['Lemon', 'Lime']),
('Lima', 'Produce', ARRAY['Key Lime', 'Persian Lime']),
('Naranja', 'Produce', ARRAY['Orange', 'Navel Orange']),
('Toronja', 'Produce', ARRAY['Grapefruit']),
('Coco', 'Produce', ARRAY['Coconut', 'Coconut Meat']),
('Mandarina', 'Produce', ARRAY['Tangerine', 'Mandarin']),
('Manzana', 'Produce', ARRAY['Apple']),
('Pera', 'Produce', ARRAY['Pear']),
('Uva', 'Produce', ARRAY['Grape', 'Grapes']),
('Ciruela', 'Produce', ARRAY['Plum']),
('Melón', 'Produce', ARRAY['Cantaloupe', 'Honeydew']),
('Sandía', 'Produce', ARRAY['Watermelon']),
('Fruta del dragon', 'Produce', ARRAY['Dragon Fruit']),
('Pitahaya', 'Produce', ARRAY['Dragon Fruit', 'Pitaya']),
('Níspero', 'Produce', ARRAY['Loquat']),
('Anona', 'Produce', ARRAY['Custard Apple', 'Cherimoya']),
('Chirimoya', 'Produce', ARRAY['Custard Apple']),
('Mamey', 'Produce', ARRAY['Mamey Sapote']),
('Zapote', 'Produce', ARRAY['Sapote', 'Black Sapote']),
('Nanche', 'Produce', ARRAY['Nance']),
('Tamarindo', 'Produce', ARRAY['Tamarind', 'Tamarind Paste']),

-- Herbs & Spices
('Cilantro', 'Produce', ARRAY['Cilantro', 'Coriander', 'Fresh Coriander']),
('Perejil', 'Produce', ARRAY['Parsley', 'Fresh Parsley']),
('Epazote', 'Produce', ARRAY['Epazote', 'Mexican Tea']),
('Hierbabuena', 'Produce', ARRAY['Mint', 'Spearmint', 'Fresh Mint']),
('Menta', 'Produce', ARRAY['Mint']),
('Orégano', 'Pantry', ARRAY['Oregano', 'Mexican Oregano']),
('Comino', 'Pantry', ARRAY['Cumin', 'Ground Cumin']),
('Pimentón', 'Pantry', ARRAY['Paprika', 'Smoked Paprika']),
('Achiote', 'Pantry', ARRAY['Annatto', 'Achiote Seeds']),
('Canela', 'Pantry', ARRAY['Cinnamon', 'Ground Cinnamon']),
('Clavo', 'Pantry', ARRAY['Cloves', 'Whole Cloves']),
('Nuez moscada', 'Pantry', ARRAY['Nutmeg', 'Ground Nutmeg']),
('Curry', 'Pantry', ARRAY['Curry Powder']),
('Chile en polvo', 'Pantry', ARRAY['Chili Powder']),
('Cúrcuma', 'Pantry', ARRAY['Turmeric', 'Ground Turmeric']),
('Jengibre', 'Produce', ARRAY['Ginger', 'Fresh Ginger']),
('Ajo en polvo', 'Pantry', ARRAY['Garlic Powder']),
('Cebolla en polvo', 'Pantry', ARRAY['Onion Powder']),
('Sal marina', 'Pantry', ARRAY['Sea Salt', 'Kosher Salt']),
('Pimienta negra', 'Pantry', ARRAY['Black Pepper', 'Ground Pepper']),

-- Pantry Items
('Frijoles negros', 'Legumes', ARRAY['Black Beans']),
('Salsa de tomate', 'Pantry', ARRAY['Tomato Sauce', 'Salsa']),
('Salsa dechile', 'Pantry', ARRAY['Hot Sauce', 'Chili Sauce']),
('Salsa inglès', 'Pantry', ARRAY['Worcestershire Sauce']),
('Salsa de soja', 'Pantry', ARRAY['Soy Sauce']),
('Mantequilla', 'Dairy', ARRAY['Butter']),
('Queso fresco', 'Dairy', ARRAY['Fresh Cheese', 'Mexican Cheese']),
('Queso mozzarella', 'Dairy', ARRAY['Mozzarella']),
('Queso cheddar', 'Dairy', ARRAY['Cheddar', 'Cheddar Cheese']),
('Crema', 'Dairy', ARRAY['Sour Cream', 'Crema Mexicana']),
('Leche', 'Dairy', ARRAY['Milk']),
('Leche de coco', 'Pantry', ARRAY['Coconut Milk']),
('Leche condensada', 'Dairy', ARRAY['Sweetened Condensed Milk']),
('Yogur', 'Dairy', ARRAY['Yogurt']),
('Huevo', 'Protein', ARRAY['Egg', 'Eggs']),
('Huevos', 'Protein', ARRAY['Eggs']),
('Miel', 'Pantry', ARRAY['Honey', 'Raw Honey']),
('Azúcar', 'Pantry', ARRAY['Sugar', 'White Sugar']),
('Azúcar morena', 'Pantry', ARRAY['Brown Sugar']),
('Azúcar glass', 'Pantry', ARRAY['Powdered Sugar', 'Confectioners Sugar']),
('Vainilla', 'Pantry', ARRAY['Vanilla', 'Vanilla Extract']),
('Chocolate', 'Pantry', ARRAY['Dark Chocolate', 'Bittersweet Chocolate']),
('Chocolate para mesa', 'Pantry', ARRAY['Mexican Chocolate', 'Table Chocolate']),
('Cacao', 'Pantry', ARRAY['Cocoa', 'Cocoa Powder']),
('Café', 'Pantry', ARRAY['Coffee', 'Espresso']),
('Harina', 'Grains', ARRAY['Flour', 'All-Purpose Flour']),
('Harina de maíz', 'Grains', ARRAY['Masa', 'Corn Flour']),
('Tortilla', 'Grains', ARRAY['Tortilla', 'Corn Tortilla']),
('Tortilla de harina', 'Grains', ARRAY['Flour Tortilla']),
('Masa', 'Grains', ARRAY['Dough', 'Tortilla Dough']),
('Maicena', 'Pantry', ARRAY['Cornstarch']),
('Levadura', 'Pantry', ARRAY['Yeast', 'Active Dry Yeast']),
('Polvo de hornear', 'Pantry', ARRAY['Baking Powder']),
('Bicarbonato', 'Pantry', ARRAY['Baking Soda']),
('Vinagre', 'Pantry', ARRAY['Vinegar']),
('Vinagre de manzana', 'Pantry', ARRAY['Apple Cider Vinegar']),
('Vinagre blanco', 'Pantry', ARRAY['White Vinegar']),
('Alcohol', 'Pantry', ARRAY['Alcohol', 'Vodka', 'Rum']),
('Ron', 'Pantry', ARRAY['Rum']),
('Tequila', 'Pantry', ARRAY['Tequila']),
('Mezcal', 'Pantry', ARRAY['Mezcal']),
('Cerveza', 'Pantry', ARRAY['Beer']),
('Caldo', 'Pantry', ARRAY['Broth', 'Stock', 'Chicken Broth']),
('Consomé', 'Pantry', ARRAY['Consomme', 'Broth']),
('Knorr suizo', 'Pantry', ARRAY['Knorr', 'Bouillon Cube']),
('Cubitos de caldo', 'Pantry', ARRAY['Bouillon Cubes', 'Stock Cubes']),
('Mayonesa', 'Pantry', ARRAY['Mayonnaise', 'Mayo']),
('Mostaza', 'Pantry', ARRAY['Mustard']),
('Catsup', 'Pantry', ARRAY['Ketchup']),
('Mermelada', 'Pantry', ARRAY['Jam', 'Preserve']),
('Arequipe', 'Pantry', ARRAY['Cajeta', 'Milk Caramel', 'Dulce de Leche']),
('Dulce de leche', 'Pantry', ARRAY['Cajeta', 'Milk Caramel']),
('Leche evaporada', 'Dairy', ARRAY['Evaporated Milk']),
('Leche condensada', 'Dairy', ARRAY['Condensed Milk']),
('Nata', 'Dairy', ARRAY['Heavy Cream', 'Whipping Cream']),
('Queso rallado', 'Dairy', ARRAY['Grated Cheese', 'Shredded Cheese']),
('Queso parmesan', 'Dairy', ARRAY['Parmesan', 'Parmigiano']),
('Requesón', 'Dairy', ARRAY['Ricotta', 'Cottage Cheese']),
('Nata para montar', 'Dairy', ARRAY['Whipped Cream']),

-- Grains & Starches
('Arroz', 'Grains', ARRAY['Rice', 'White Rice']),
('Arroz integral', 'Grains', ARRAY['Brown Rice']),
('Fideos', 'Grains', ARRAY['Pasta', 'Noodles', 'Short Pasta']),
('Tallarines', 'Grains', ARRAY['Noodles', 'Pasta']),
('Avena', 'Grains', ARRAY['Oats', 'Rolled Oats']),
('Trigo', 'Grains', ARRAY['Wheat']),
(' sémola', 'Grains', ARRAY['Semolina']),
('Granola', 'Grains', ARRAY['Granola']);
