-- Seed file with 500+ common pantry ingredients
-- Run this in Supabase SQL Editor after the main schema

-- Produce
INSERT INTO ingredients (name, category, aliases) VALUES
('Apple', 'Produce', ARRAY['Apples', 'Red Apple', 'Green Apple']),
('Banana', 'Produce', ARRAY['Bananas', 'Plantain']),
('Orange', 'Produce', ARRAY['Oranges', 'Navel Orange', 'Blood Orange']),
('Lemon', 'Produce', ARRAY['Lemons', 'Lemon juice']),
('Lime', 'Produce', ARRAY['Limes', 'Lime juice']),
('Grape', 'Produce', ARRAY['Grapes', 'Green Grapes', 'Red Grapes']),
('Strawberry', 'Produce', ARRAY['Strawberries']),
('Blueberry', 'Produce', ARRAY['Blueberries']),
('Raspberry', 'Produce', ARRAY['Raspberries']),
('Blackberry', 'Produce', ARRAY['Blackberries']),
('Avocado', 'Produce', ARRAY['Avocados', 'Avo']),
('Tomato', 'Produce', ARRAY['Tomatoes', 'Cherry Tomatoes', 'Roma Tomato']),
('Potato', 'Produce', ARRAY['Potatoes', 'Russet Potato', 'Red Potato']),
('Onion', 'Produce', ARRAY['Onions', 'Yellow Onion', 'White Onion', 'Red Onion']),
('Garlic', 'Produce', ARRAY['Garlic cloves', 'Garlic bulb']),
('Ginger', 'Produce', ARRAY['Fresh Ginger', 'Ground Ginger']),
('Carrot', 'Produce', ARRAY['Carrots']),
('Celery', 'Produce', ARRAY['Celery stalks']),
('Bell Pepper', 'Produce', ARRAY['Peppers', 'Red Pepper', 'Green Pepper']),
('Broccoli', 'Produce', ARRAY['Broccoli florets']),
('Cauliflower', 'Produce', ARRAY['Cauliflower florets']),
('Spinach', 'Produce', ARRAY['Baby Spinach', 'Fresh Spinach']),
('Kale', 'Produce', ARRAY['Curly Kale', 'Lacinato Kale']),
('Lettuce', 'Produce', ARRAY['Romaine', 'Iceberg']),
('Cucumber', 'Produce', ARRAY['Cucumbers']),
('Zucchini', 'Produce', ARRAY['Courgette']),
('Mushroom', 'Produce', ARRAY['Mushrooms', 'Button Mushroom', 'Cremini', 'Portobello']),
('Asparagus', 'Produce', ARRAY['Asparagus spears']),
('Green Bean', 'Produce', ARRAY['Green Beans']),
('Pea', 'Produce', ARRAY['Peas', 'Green Peas']),
('Corn', 'Produce', ARRAY['Sweet Corn', 'Corn kernels']),
('Cabbage', 'Produce', ARRAY['Green Cabbage', 'Red Cabbage']),
('Brussels Sprout', 'Produce', ARRAY['Brussels Sprouts']),
('Sweet Potato', 'Produce', ARRAY['Sweet Potatoes', 'Yam']),
('Butternut Squash', 'Produce', ARRAY['Butternut']),
('Coconut', 'Produce', ARRAY['Coconut meat', 'Coconut milk']),
('Pineapple', 'Produce', ARRAY['Pineapple chunks']),
('Mango', 'Produce', ARRAY['Mangoes']),
('Papaya', 'Produce', ARRAY['Papayas']),
('Kiwi', 'Produce', ARRAY['Kiwis']),
('Watermelon', 'Produce', ARRAY['Watermelon chunks']),
('Peach', 'Produce', ARRAY['Peaches']),
('Pear', 'Produce', ARRAY['Pears']),
('Date', 'Produce', ARRAY['Dates', 'Medjool Date']),
('Raisin', 'Produce', ARRAY['Raisins', 'Golden Raisins']),
('Cranberry', 'Produce', ARRAY['Cranberries', 'Dried Cranberries']),
('Basil', 'Produce', ARRAY['Fresh Basil', 'Thai Basil']),
('Cilantro', 'Produce', ARRAY['Coriander', 'Fresh Cilantro']),
('Parsley', 'Produce', ARRAY['Fresh Parsley', 'Italian Parsley']),
('Mint', 'Produce', ARRAY['Fresh Mint', 'Spearmint']),
('Rosemary', 'Produce', ARRAY['Fresh Rosemary']),
('Thyme', 'Produce', ARRAY['Fresh Thyme']),
('Oregano', 'Produce', ARRAY['Fresh Oregano']),
('Sage', 'Produce', ARRAY['Fresh Sage']),
('Dill', 'Produce', ARRAY['Fresh Dill']),
('Chives', 'Produce', ARRAY['Fresh Chives']),
('Bay Leaf', 'Produce', ARRAY['Bay Leaves']),
('Caper', 'Produce', ARRAY['Capers']),
('Olive', 'Produce', ARRAY['Olives', 'Kalamata']),
('Pickle', 'Produce', ARRAY['Pickles', 'Dill Pickle']),
('Jalapeño', 'Produce', ARRAY['Jalapeños']),
('Chili Powder', 'Produce', ARRAY['Chile powder']),
('Paprika', 'Produce', ARRAY['Smoked Paprika', 'Sweet Paprika']),
('Cayenne', 'Produce', ARRAY['Cayenne Pepper']),
('Red Pepper Flake', 'Produce', ARRAY['Crushed Red Pepper']),
('Black Pepper', 'Produce', ARRAY['Black Peppercorn']),
('Salt', 'Produce', ARRAY['Sea Salt', 'Kosher Salt']),
('Flour', 'Produce', ARRAY['All-purpose Flour', 'AP Flour']),
('Sugar', 'Produce', ARRAY['White Sugar', 'Granulated Sugar']),
('Brown Sugar', 'Produce', ARRAY['Brown Sugar']),
('Powdered Sugar', 'Produce', ARRAY['Confectioners Sugar']),
('Honey', 'Produce', ARRAY['Raw Honey']),
('Maple Syrup', 'Produce', ARRAY['Pure Maple Syrup']),
('Molasses', 'Produce', ARRAY['Blackstrap Molasses']),
('Vanilla Extract', 'Produce', ARRAY['Pure Vanilla Extract']),
('Cocoa Powder', 'Produce', ARRAY['Unsweetened Cocoa']),
('Chocolate Chips', 'Produce', ARRAY['Chocolate chips']),
('Baking Soda', 'Produce', ARRAY['Baking soda']),
('Baking Powder', 'Produce', ARRAY['Baking powder']),
('Yeast', 'Produce', ARRAY['Active Dry Yeast', 'Instant Yeast']),
('Rice', 'Produce', ARRAY['White Rice', 'Long grain rice']),
('Basmati Rice', 'Produce', ARRAY['Basmati']),
('Jasmine Rice', 'Produce', ARRAY['Jasmine']),
('Brown Rice', 'Produce', ARRAY['Brown rice']),
('Arborio Rice', 'Produce', ARRAY['Arborio', 'Risotto rice']),
('Pasta', 'Produce', ARRAY['Pasta', 'Spaghetti', 'Penne']),
('Egg Noodle', 'Produce', ARRAY['Egg Noodles']),
('Rice Noodle', 'Produce', ARRAY['Rice Noodles', 'Rice vermicelli']),
('Couscous', 'Produce', ARRAY['Couscous']),
('Quinoa', 'Produce', ARRAY['Quinoa']),
('Farro', 'Produce', ARRAY['Farro']),
('Barley', 'Produce', ARRAY['Pearl Barley']),
('Bread Crumb', 'Produce', ARRAY['Breadcrumbs', 'Panko']),
('Tortilla', 'Produce', ARRAY['Tortillas', 'Corn Tortilla']),
-- Dairy
('Milk', 'Dairy', ARRAY['Whole Milk', '2% Milk']),
('Heavy Cream', 'Dairy', ARRAY['Heavy Cream', 'Whipping cream']),
('Half and Half', 'Dairy', ARRAY['Half & Half']),
('Buttermilk', 'Dairy', ARRAY['Buttermilk']),
('Sour Cream', 'Dairy', ARRAY['Sour cream']),
('Cream Cheese', 'Dairy', ARRAY['Cream cheese']),
('Greek Yogurt', 'Dairy', ARRAY['Greek yogurt']),
('Yogurt', 'Dairy', ARRAY['Yogurt']),
('Cottage Cheese', 'Dairy', ARRAY['Cottage cheese']),
('Ricotta', 'Dairy', ARRAY['Ricotta']),
('Cheddar', 'Dairy', ARRAY['Cheddar', 'Sharp cheddar']),
('Mozzarella', 'Dairy', ARRAY['Mozzarella']),
('Parmesan', 'Dairy', ARRAY['Parmesan', 'Parmigiano-Reggiano']),
('Feta', 'Dairy', ARRAY['Feta']),
('Goat Cheese', 'Dairy', ARRAY['Goat cheese']),
('Brie', 'Dairy', ARRAY['Brie']),
('Swiss', 'Dairy', ARRAY['Swiss cheese']),
('Butter', 'Dairy', ARRAY['Butter', 'Unsalted butter']),
('Ghee', 'Dairy', ARRAY['Ghee']),
('Egg', 'Dairy', ARRAY['Eggs', 'Large eggs']),
('Egg White', 'Dairy', ARRAY['Egg whites']),
('Egg Yolk', 'Dairy', ARRAY['Egg yolks']),
-- Meat
('Beef', 'Meat', ARRAY['Ground Beef', 'Beef']),
('Ground Beef', 'Meat', ARRAY['Minced beef']),
('Beef Steak', 'Meat', ARRAY['Steak', 'Ribeye', 'Sirloin']),
('Beef Chuck', 'Meat', ARRAY['Chuck roast']),
('Beef Brisket', 'Meat', ARRAY['Brisket']),
('Pork', 'Meat', ARRAY['Pork loin', 'Pork chop']),
('Pork Belly', 'Meat', ARRAY['Pork belly']),
('Bacon', 'Meat', ARRAY['Bacon']),
('Ham', 'Meat', ARRAY['Ham']),
('Prosciutto', 'Meat', ARRAY['Parma ham']),
('Pancetta', 'Meat', ARRAY['Pancetta']),
('Sausage', 'Meat', ARRAY['Sausages', 'Italian sausage']),
('Chorizo', 'Meat', ARRAY['Chorizo']),
('Lamb', 'Meat', ARRAY['Lamb chops', 'Lamb leg']),
('Chicken Breast', 'Meat', ARRAY['Chicken breasts']),
('Chicken Thigh', 'Meat', ARRAY['Chicken thighs']),
('Chicken Wing', 'Meat', ARRAY['Chicken wings']),
('Ground Chicken', 'Meat', ARRAY['Ground chicken']),
('Turkey', 'Meat', ARRAY['Turkey', 'Ground turkey']),
('Duck', 'Meat', ARRAY['Duck breast']),
('Venison', 'Meat', ARRAY['Venison']),
('Bison', 'Meat', ARRAY['Bison']),
-- Seafood
('Salmon', 'Seafood', ARRAY['Salmon fillet', 'Atlantic salmon']),
('Tuna', 'Seafood', ARRAY['Tuna', 'Ahi tuna']),
('Cod', 'Seafood', ARRAY['Cod fillet']),
('Tilapia', 'Seafood', ARRAY['Tilapia']),
('Halibut', 'Seafood', ARRAY['Halibut']),
('Trout', 'Seafood', ARRAY['Trout']),
('Swordfish', 'Seafood', ARRAY['Swordfish']),
('Mahi Mahi', 'Seafood', ARRAY['Mahi']),
('Snapper', 'Seafood', ARRAY['Snapper']),
('Sea Bass', 'Seafood', ARRAY['Sea bass']),
('Sardine', 'Seafood', ARRAY['Sardines']),
('Anchovy', 'Seafood', ARRAY['Anchovies']),
('Smoked Salmon', 'Seafood', ARRAY['Smoked salmon', 'Lox']),
('Crab', 'Seafood', ARRAY['Crab meat', 'Dungeness crab']),
('Lobster', 'Seafood', ARRAY['Lobster']),
('Shrimp', 'Seafood', ARRAY['Shrimp', 'Prawns']),
('Scallop', 'Seafood', ARRAY['Scallops']),
('Mussel', 'Seafood', ARRAY['Mussels']),
('Clam', 'Seafood', ARRAY['Clams']),
('Oyster', 'Seafood', ARRAY['Oysters']),
('Squid', 'Seafood', ARRAY['Calamari', 'Squid']),
('Octopus', 'Seafood', ARRAY['Octopus']),
-- Grains
('Oat', 'Grains', ARRAY['Oats', 'Rolled oats']),
('Cornmeal', 'Grains', ARRAY['Polenta']),
('Grits', 'Grains', ARRAY['Grits']),
('Sesame Seed', 'Grains', ARRAY['Sesame seeds']),
('Sunflower Seed', 'Grains', ARRAY['Sunflower seeds']),
('Pumpkin Seed', 'Grains', ARRAY['Pepitas']),
('Chia Seed', 'Grains', ARRAY['Chia seeds']),
('Flaxseed', 'Grains', ARRAY['Flax seeds']),
('Poppy Seed', 'Grains', ARRAY['Poppy seeds']),
('Cumin', 'Grains', ARRAY['Cumin', 'Cumin seeds']),
('Cinnamon', 'Grains', ARRAY['Cinnamon', 'Ground cinnamon']),
('Curry Powder', 'Grains', ARRAY['Curry powder']),
('Almond', 'Grains', ARRAY['Almonds']),
('Walnut', 'Grains', ARRAY['Walnuts']),
('Pecan', 'Grains', ARRAY['Pecans']),
('Cashew', 'Grains', ARRAY['Cashews']),
('Pistachio', 'Grains', ARRAY['Pistachios']),
('Hazelnut', 'Grains', ARRAY['Hazelnuts']),
('Peanut', 'Grains', ARRAY['Peanuts']),
('Peanut Butter', 'Grains', ARRAY['Peanut butter']),
('Tahini', 'Grains', ARRAY['Tahini']),
-- Condiments
('Ketchup', 'Condiments', ARRAY['Tomato ketchup']),
('Mustard', 'Condiments', ARRAY['Mustard', 'Yellow mustard', 'Dijon']),
('Mayonnaise', 'Condiments', ARRAY['Mayo']),
('Hot Sauce', 'Condiments', ARRAY['Hot sauce']),
('Sriracha', 'Condiments', ARRAY['Sriracha']),
('Soy Sauce', 'Condiments', ARRAY['Soy sauce']),
('Worcestershire', 'Condiments', ARRAY['Worcestershire sauce']),
('Fish Sauce', 'Condiments', ARRAY['Fish sauce']),
('Oyster Sauce', 'Condiments', ARRAY['Oyster sauce']),
('Hoisin', 'Condiments', ARRAY['Hoisin sauce']),
('Teriyaki', 'Condiments', ARRAY['Teriyaki sauce']),
('BBQ Sauce', 'Condiments', ARRAY['Barbecue sauce']),
('Gochujang', 'Condiments', ARRAY['Gochujang']),
('Miso Paste', 'Condiments', ARRAY['Miso']),
('Salsa', 'Condiments', ARRAY['Salsa']),
('Guacamole', 'Condiments', ARRAY['Guacamole']),
('Ranch', 'Condiments', ARRAY['Ranch dressing']),
('Italian Dressing', 'Condiments', ARRAY['Italian dressing']),
('Balsamic Vinegar', 'Condiments', ARRAY['Balsamic']),
('Rice Vinegar', 'Condiments', ARRAY['Rice vinegar']),
('Olive Oil', 'Condiments', ARRAY['Olive oil']),
('Extra Virgin Olive Oil', 'Condiments', ARRAY['EVOO']),
('Vegetable Oil', 'Condiments', ARRAY['Canola oil']),
('Coconut Oil', 'Condiments', ARRAY['Coconut oil']),
('Sesame Oil', 'Condiments', ARRAY['Sesame oil']),
('Pesto', 'Condiments', ARRAY['Basil pesto']),
('Hummus', 'Condiments', ARRAY['Hummus']),
('Chicken Stock', 'Condiments', ARRAY['Chicken broth']),
('Beef Stock', 'Condiments', ARRAY['Beef broth']),
('Vegetable Stock', 'Condiments', ARRAY['Vegetable broth']),
('Tomato Paste', 'Condiments', ARRAY['Tomato paste']),
('Tomato Sauce', 'Condiments', ARRAY['Marinara']),
-- Frozen
('Frozen Fruit', 'Frozen', ARRAY['Frozen berries']),
('Frozen Vegetables', 'Frozen', ARRAY['Frozen veggies']),
('Frozen Peas', 'Frozen', ARRAY['Frozen peas']),
('Frozen Corn', 'Frozen', ARRAY['Frozen corn']),
('Ice Cream', 'Frozen', ARRAY['Ice cream']),
('Frozen Pizza', 'Frozen', ARRAY['Frozen pizza']),
-- Canned
('Canned Tomatoes', 'Canned', ARRAY['Diced tomatoes', 'Crushed tomatoes']),
('Canned Beans', 'Canned', ARRAY['Kidney beans', 'Black beans']),
('Canned Chickpeas', 'Canned', ARRAY['Chickpeas', 'Garbanzo']),
('Canned Corn', 'Canned', ARRAY['Corn kernels']),
('Canned Tuna', 'Canned', ARRAY['Canned tuna']),
('Coconut Milk', 'Canned', ARRAY['Canned coconut milk']),
('Canned Pumpkin', 'Canned', ARRAY['Pumpkin puree']),
-- Additional Produce
('Artichoke', 'Produce', ARRAY['Artichokes', 'Artichoke hearts']),
('Arugula', 'Produce', ARRAY['Arugula', 'Rocket']),
('Beet', 'Produce', ARRAY['Beets', 'Beetroot']),
('Bok Choy', 'Produce', ARRAY['Bok choy', 'Pak choi']),
('Broccoli Rabe', 'Produce', ARRAY['Broccoli rabe', 'Rapini']),
('Celery Root', 'Produce', ARRAY['Celery root', 'Celeriac']),
('Chard', 'Produce', ARRAY['Swiss chard']),
('Chayote', 'Produce', ARRAY['Chayote']),
('Collard Greens', 'Produce', ARRAY['Collard greens']),
('Daikon', 'Produce', ARRAY['Daikon', 'Daikon radish']),
('Eggplant', 'Produce', ARRAY['Eggplant', 'Aubergine']),
('Endive', 'Produce', ARRAY['Endive']),
('Escarole', 'Produce', ARRAY['Escarole']),
('Fennel', 'Produce', ARRAY['Fennel', 'Fennel bulb']),
('Hearts of Palm', 'Produce', ARRAY['Hearts of palm']),
('Jicama', 'Produce', ARRAY['Jicama']),
('Kohlrabi', 'Produce', ARRAY['Kohlrabi']),
('Leek', 'Produce', ARRAY['Leeks']),
('Napa Cabbage', 'Produce', ARRAY['Napa cabbage', 'Chinese cabbage']),
('Okra', 'Produce', ARRAY['Okra']),
('Parsnip', 'Produce', ARRAY['Parsnips']),
('Rutabaga', 'Produce', ARRAY['Rutabaga']),
('Salsify', 'Produce', ARRAY['Salsify']),
('Scallion', 'Produce', ARRAY['Scallions', 'Green onions']),
('Snow Peas', 'Produce', ARRAY['Snow peas', 'Mange tout']),
('Spaghetti Squash', 'Produce', ARRAY['Spaghetti squash']),
('Sugar Snap Peas', 'Produce', ARRAY['Sugar snap peas']),
('Tomatillo', 'Produce', ARRAY['Tomatillos']),
('Turnip', 'Produce', ARRAY['Turnips']),
('Watercress', 'Produce', ARRAY['Watercress']),
('Zucchini Blossom', 'Produce', ARRAY['Zucchini blossoms']),
('Chanterelle', 'Produce', ARRAY['Chanterelle mushrooms']),
('Morel', 'Produce', ARRAY['Morel mushrooms']),
('Porcini', 'Produce', ARRAY['Porcini mushrooms']),
('Shiitake', 'Produce', ARRAY['Shiitake mushrooms']),
('Trumpet Mushroom', 'Produce', ARRAY['King oyster mushrooms']),
('Lemongrass', 'Produce', ARRAY['Lemongrass']),
('Tarragon', 'Produce', ARRAY['Fresh tarragon']),
('Marjoram', 'Produce', ARRAY['Fresh marjoram']),
('Chervil', 'Produce', ARRAY['Fresh chervil']),
('Lemon Verbena', 'Produce', ARRAY['Lemon verbena']),
('Sorrel', 'Produce', ARRAY['Sorrel']),
('Borage', 'Produce', ARRAY['Borage']),
('Lemon Balm', 'Produce', ARRAY['Lemon balm']),
('Angostura Bitters', 'Produce', ARRAY['Angostura bitters']),
('Five Spice', 'Produce', ARRAY['Chinese five spice']),
('Garam Masala', 'Produce', ARRAY['Garam masala']),
('Italian Seasoning', 'Produce', ARRAY['Italian seasoning']),
('Old Bay Seasoning', 'Produce', ARRAY['Old Bay']),
('Taco Seasoning', 'Produce', ARRAY['Taco seasoning']),
('Creole Seasoning', 'Produce', ARRAY['Creole seasoning']),
('Everything Bagel Seasoning', 'Produce', ARRAY['Everything bagel seasoning']),
('Zaatar', 'Produce', ARRAY['Zaatar']),
('Sumac', 'Produce', ARRAY['Sumac']),
('Truffle Oil', 'Produce', ARRAY['Truffle oil']),
('Truffle Salt', 'Produce', ARRAY['Truffle salt']),
('Fleur de Sel', 'Produce', ARRAY['Fleur de sel']),
('Himalayan Pink Salt', 'Produce', ARRAY['Himalayan salt']),
('Smoked Salt', 'Produce', ARRAY['Smoked salt']),
('Flake Salt', 'Produce', ARRAY['Flake salt']),
('Celtic Sea Salt', 'Produce', ARRAY['Celtic sea salt']),
('White Pepper', 'Produce', ARRAY['White peppercorn']),
('Green Peppercorn', 'Produce', ARRAY['Green peppercorns']),
('Pink Peppercorn', 'Produce', ARRAY['Pink peppercorns']),
('Sichuan Peppercorn', 'Produce', ARRAY['Sichuan peppercorns']),
('Juniper Berry', 'Produce', ARRAY['Juniper berries']),
('Allspice', 'Produce', ARRAY['Allspice', 'Pimento']),
('Anise', 'Produce', ARRAY['Anise seeds']),
('Caraway', 'Produce', ARRAY['Caraway seeds']),
('Cardamom', 'Produce', ARRAY['Cardamom', 'Green cardamom']),
('Clove', 'Produce', ARRAY['Cloves']),
('Coriander Seed', 'Produce', ARRAY['Coriander seeds']),
('Dill Seed', 'Produce', ARRAY['Dill seeds']),
('Fennel Seed', 'Produce', ARRAY['Fennel seeds']),
('Fenugreek', 'Produce', ARRAY['Fenugreek seeds']),
('Mustard Seed', 'Produce', ARRAY['Mustard seeds', 'Yellow mustard seed']),
('Nigella', 'Produce', ARRAY['Nigella seeds', 'Black cumin']),
('Nutmeg', 'Produce', ARRAY['Nutmeg']),
('Saffron', 'Produce', ARRAY['Saffron']),
('Star Anise', 'Produce', ARRAY['Star anise']),
('Turmeric', 'Produce', ARRAY['Turmeric', 'Ground turmeric']),
('Wasabi', 'Produce', ARRAY['Wasabi']),
('Horseradish', 'Produce', ARRAY['Horseradish']),
('Rhubarb', 'Produce', ARRAY['Rhubarb']),
('Persimmon', 'Produce', ARRAY['Persimmon']),
('Pomegranate', 'Produce', ARRAY['Pomegranate']),
('Passion Fruit', 'Produce', ARRAY['Passion fruit']),
('Fig', 'Produce', ARRAY['Figs']),
('Nectarine', 'Produce', ARRAY['Nectarines']),
('Apricot', 'Produce', ARRAY['Apricots']),
('Plum', 'Produce', ARRAY['Plums']),
('Cherries', 'Produce', ARRAY['Cherries']),
('Cantaloupe', 'Produce', ARRAY['Cantaloupe']),
('Honeydew', 'Produce', ARRAY['Honeydew']),
('Grapefruit', 'Produce', ARRAY['Grapefruit']),
('Tangerine', 'Produce', ARRAY['Tangerines']),
('Clementine', 'Produce', ARRAY['Clementines']),
('Kumquat', 'Produce', ARRAY['Kumquats']),
('Dragon Fruit', 'Produce', ARRAY['Dragon fruit']),
('Star Fruit', 'Produce', ARRAY['Star fruit']),
('Lychee', 'Produce', ARRAY['Lychees']),
('Longan', 'Produce', ARRAY['Longans']),
('Jackfruit', 'Produce', ARRAY['Jackfruit']),
('Breadfruit', 'Produce', ARRAY['Breadfruit']),
('Plantain', 'Produce', ARRAY['Plantains']),
('Chicory', 'Produce', ARRAY['Chicory']),
('Radicchio', 'Produce', ARRAY['Radicchio']),
('Frisee', 'Produce', ARRAY['Frisee']),
('Mache', 'Produce', ARRAY['Mache', 'Corn salad']),
('Mesclun', 'Produce', ARRAY['Mesclun']),
('Butter Lettuce', 'Produce', ARRAY['Butter lettuce', 'Bibb lettuce']),
('Pomegranate Seeds', 'Produce', ARRAY['Pomegranate arils']),
-- Additional Dairy
('Evaporated Milk', 'Dairy', ARRAY['Evaporated milk']),
('Condensed Milk', 'Dairy', ARRAY['Sweetened condensed milk']),
('Almond Milk', 'Dairy', ARRAY['Almond milk']),
('Oat Milk', 'Dairy', ARRAY['Oat milk']),
('Soy Milk', 'Dairy', ARRAY['Soy milk']),
('Cashew Milk', 'Dairy', ARRAY['Cashew milk']),
('Rice Milk', 'Dairy', ARRAY['Rice milk']),
('Coconut Cream', 'Dairy', ARRAY['Coconut cream']),
('Crème Fraîche', 'Dairy', ARRAY['Creme fraiche']),
('Mascarpone', 'Dairy', ARRAY['Mascarpone']),
('Provolone', 'Dairy', ARRAY['Provolone']),
('Gruyere', 'Dairy', ARRAY['Gruyere']),
('Manchego', 'Dairy', ARRAY['Manchego']),
('Pecorino', 'Dairy', ARRAY['Pecorino romano']),
('Blue Cheese', 'Dairy', ARRAY['Blue cheese', 'Roquefort']),
('Gorgonzola', 'Dairy', ARRAY['Gorgonzola']),
('Stilton', 'Dairy', ARRAY['Stilton']),
('Camembert', 'Dairy', ARRAY['Camembert']),
('Taleggio', 'Dairy', ARRAY['Taleggio']),
('Fontina', 'Dairy', ARRAY['Fontina']),
('Gouda', 'Dairy', ARRAY['Gouda']),
('Edam', 'Dairy', ARRAY['Edam']),
('Colby', 'Dairy', ARRAY['Colby']),
('Monterey Jack', 'Dairy', ARRAY['Monterey Jack']),
('Pepper Jack', 'Dairy', ARRAY['Pepper jack']),
('Havarti', 'Dairy', ARRAY['Havarti']),
('Muenster', 'Dairy', ARRAY['Muenster']),
('Queso Fresco', 'Dairy', ARRAY['Queso fresco']),
('Cotija', 'Dairy', ARRAY['Cotija']),
('Paneer', 'Dairy', ARRAY['Paneer']),
('Halloumi', 'Dairy', ARRAY['Halloumi']),
('Burrata', 'Dairy', ARRAY['Burrata']),
('Clarified Butter', 'Dairy', ARRAY['Clarified butter']),
('Brown Butter', 'Dairy', ARRAY['Brown butter']),
('Duck Fat', 'Dairy', ARRAY['Duck fat']),
('Lard', 'Dairy', ARRAY['Lard']),
('Beef Tallow', 'Dairy', ARRAY['Beef tallow']),
('Quail Egg', 'Dairy', ARRAY['Quail eggs']),
('Duck Egg', 'Dairy', ARRAY['Duck eggs']),
-- Additional Meat
('Beef Tenderloin', 'Meat', ARRAY['Beef tenderloin', 'Filet mignon']),
('Beef Ribeye', 'Meat', ARRAY['Ribeye steak']),
('Beef Sirloin', 'Meat', ARRAY['Sirloin steak']),
('Beef Flank', 'Meat', ARRAY['Flank steak']),
('Beef Skirt', 'Meat', ARRAY['Skirt steak']),
('Beef Short Ribs', 'Meat', ARRAY['Short ribs']),
('Beef Oxtail', 'Meat', ARRAY['Oxtail']),
('Beef Liver', 'Meat', ARRAY['Beef liver']),
('Beef Tongue', 'Meat', ARRAY['Beef tongue']),
('Beef Heart', 'Meat', ARRAY['Beef heart']),
('Pork Tenderloin', 'Meat', ARRAY['Pork tenderloin']),
('Pork Loin Chops', 'Meat', ARRAY['Pork loin chops']),
('Pork Shoulder', 'Meat', ARRAY['Pork shoulder', 'Pork butt']),
('Pork Leg', 'Meat', ARRAY['Pork leg', 'Ham']),
('Pork Liver', 'Meat', ARRAY['Pork liver']),
('Pork Feet', 'Meat', ARRAY['Pork feet']),
('Pork Ears', 'Meat', ARRAY['Pork ears']),
('Lamb Rack', 'Meat', ARRAY['Rack of lamb']),
('Lamb Leg', 'Meat', ARRAY['Lamb leg']),
('Lamb Shoulder', 'Meat', ARRAY['Lamb shoulder']),
('Lamb Chops', 'Meat', ARRAY['Lamb chops']),
('Lamb Loin', 'Meat', ARRAY['Lamb loin']),
('Lamb Shank', 'Meat', ARRAY['Lamb shank']),
('Lamb Liver', 'Meat', ARRAY['Lamb liver']),
('Ground Lamb', 'Meat', ARRAY['Ground lamb']),
('Mutton', 'Meat', ARRAY['Mutton']),
('Goat Meat', 'Meat', ARRAY['Goat', 'Cabrito']),
('Chicken Liver', 'Meat', ARRAY['Chicken livers']),
('Chicken Heart', 'Meat', ARRAY['Chicken hearts']),
('Chicken Gizzard', 'Meat', ARRAY['Chicken gizzards']),
('Chicken Feet', 'Meat', ARRAY['Chicken feet']),
('Cornish Hen', 'Meat', ARRAY['Cornish hen']),
('Quail', 'Meat', ARRAY['Quail']),
('Pheasant', 'Meat', ARRAY['Pheasant']),
('Partridge', 'Meat', ARRAY['Partridge']),
('Rabbit', 'Meat', ARRAY['Rabbit']),
('Wild Boar', 'Meat', ARRAY['Wild boar']),
('Elk', 'Meat', ARRAY['Elk']),
('Kangaroo', 'Meat', ARRAY['Kangaroo']),
('Alligator', 'Meat', ARRAY['Alligator']),
('Frog Legs', 'Meat', ARRAY['Frog legs']),
-- Additional Seafood
('Mackerel', 'Seafood', ARRAY['Mackerel']),
('Herring', 'Seafood', ARRAY['Herring']),
('Sprat', 'Seafood', ARRAY['Sprats']),
('Eel', 'Seafood', ARRAY['Eel']),
('Flounder', 'Seafood', ARRAY['Flounder']),
('Sole', 'Seafood', ARRAY['Sole']),
('Brill', 'Seafood', ARRAY['Brill']),
('Turbot', 'Seafood', ARRAY['Turbot']),
('John Dory', 'Seafood', ARRAY['John Dory']),
('Gurnard', 'Seafood', ARRAY['Gurnard']),
('Mullet', 'Seafood', ARRAY['Mullet']),
('Sea Bream', 'Seafood', ARRAY['Sea bream']),
('Red Snapper', 'Seafood', ARRAY['Red snapper']),
('Grouper', 'Seafood', ARRAY['Grouper']),
('Marlin', 'Seafood', ARRAY['Marlin']),
('Sturgeon', 'Seafood', ARRAY['Sturgeon']),
('Catfish', 'Seafood', ARRAY['Catfish']),
('Carp', 'Seafood', ARRAY['Carp']),
('Perch', 'Seafood', ARRAY['Perch']),
('Walleye', 'Seafood', ARRAY['Walleye']),
('Pike', 'Seafood', ARRAY['Pike']),
('Bass', 'Seafood', ARRAY['Bass']),
('Crab Legs', 'Seafood', ARRAY['Crab legs']),
('Dungeness Crab', 'Seafood', ARRAY['Dungeness crab']),
('Blue Crab', 'Seafood', ARRAY['Blue crab']),
('King Crab', 'Seafood', ARRAY['King crab']),
('Snow Crab', 'Seafood', ARRAY['Snow crab']),
('Soft Shell Crab', 'Seafood', ARRAY['Soft shell crab']),
('Crayfish', 'Seafood', ARRAY['Crayfish']),
('Langoustine', 'Seafood', ARRAY['Langoustine']),
('Sea Urchin', 'Seafood', ARRAY['Sea urchin', 'Uni']),
('Abalone', 'Seafood', ARRAY['Abalone']),
('Conch', 'Seafood', ARRAY['Conch']),
('Whelk', 'Seafood', ARRAY['Whelk']),
('Periwinkle', 'Seafood', ARRAY['Periwinkles']),
('Snail', 'Seafood', ARRAY['Snails', 'Escargot']),
('Cuttlefish', 'Seafood', ARRAY['Cuttlefish']),
('Flat Squid', 'Seafood', ARRAY['Flat squid']),
('Baby Squid', 'Seafood', ARRAY['Baby squid']),
('Whole Octopus', 'Seafood', ARRAY['Whole octopus']),
('Octopus Arms', 'Seafood', ARRAY['Octopus arms']),
('Squid Ink', 'Seafood', ARRAY['Squid ink']),
('Fish Stock', 'Seafood', ARRAY['Fish stock']),
('Shrimp Stock', 'Seafood', ARRAY['Shrimp stock']),
('Lobster Stock', 'Seafood', ARRAY['Lobster stock']),
('Lobster Tail', 'Seafood', ARRAY['Lobster tails']),
-- Additional Grains
('Amaranth', 'Grains', ARRAY['Amaranth']),
('Buckwheat', 'Grains', ARRAY['Buckwheat', 'Kasha']),
('Millet', 'Grains', ARRAY['Millet']),
('Teff', 'Grains', ARRAY['Teff']),
('Spelt', 'Grains', ARRAY['Spelt']),
('Kamut', 'Grains', ARRAY['Kamut']),
('Einkorn', 'Grains', ARRAY['Einkorn']),
('Freekeh', 'Grains', ARRAY['Freekeh']),
('Bulgur', 'Grains', ARRAY['Bulgur', 'Bulgur wheat']),
('Wheat Berries', 'Grains', ARRAY['Wheat berries']),
('Wheat Germ', 'Grains', ARRAY['Wheat germ']),
('Wheat Bran', 'Grains', ARRAY['Wheat bran']),
('Corn Starch', 'Grains', ARRAY['Cornstarch']),
('Corn Flour', 'Grains', ARRAY['Corn flour', 'Masa']),
('Rice Flour', 'Grains', ARRAY['Rice flour']),
('Almond Flour', 'Grains', ARRAY['Almond flour']),
('Coconut Flour', 'Grains', ARRAY['Coconut flour']),
('Oat Flour', 'Grains', ARRAY['Oat flour']),
('Chickpea Flour', 'Grains', ARRAY['Chickpea flour', 'Besan']),
('Buckwheat Flour', 'Grains', ARRAY['Buckwheat flour']),
('Sorghum Flour', 'Grains', ARRAY['Sorghum flour']),
('Tapioca Flour', 'Grains', ARRAY['Tapioca flour']),
('Potato Starch', 'Grains', ARRAY['Potato starch']),
('Arrowroot', 'Grains', ARRAY['Arrowroot']),
('Psyllium Husk', 'Grains', ARRAY['Psyllium husk']),
('Xanthan Gum', 'Grains', ARRAY['Xanthan gum']),
('Vital Wheat Gluten', 'Grains', ARRAY['Vital wheat gluten']),
('Bread Flour', 'Grains', ARRAY['Bread flour']),
('Whole Wheat Flour', 'Grains', ARRAY['Whole wheat flour']),
('Semolina', 'Grains', ARRAY['Semolina']),
('Durum Wheat', 'Grains', ARRAY['Durum wheat']),
('Farro Flour', 'Grains', ARRAY['Farro flour']),
('Granola', 'Grains', ARRAY['Granola']),
('Muesli', 'Grains', ARRAY['Muesli']),
('Hemp Seeds', 'Grains', ARRAY['Hemp seeds', 'Hemp hearts']),
('Black Sesame Seeds', 'Grains', ARRAY['Black sesame seeds']),
('Buckwheat Groats', 'Grains', ARRAY['Buckwheat groats']),
('Steel Cut Oats', 'Grains', ARRAY['Steel cut oats']),
('Quick Oats', 'Grains', ARRAY['Quick oats']),
('Oat Bran', 'Grains', ARRAY['Oat bran']),
('Barley Groats', 'Grains', ARRAY['Barley groats']),
('Rolled Rye', 'Grains', ARRAY['Rolled rye']),
('Rye Berries', 'Grains', ARRAY['Rye berries']),
('Malt Extract', 'Grains', ARRAY['Malt extract']),
('Malt Syrup', 'Grains', ARRAY['Malt syrup']),
('Rice Syrup', 'Grains', ARRAY['Rice syrup']),
('Corn Syrup', 'Grains', ARRAY['Corn syrup']),
('Glucose Syrup', 'Grains', ARRAY['Glucose syrup']),
('Invert Sugar', 'Grains', ARRAY['Invert sugar']),
('Sucanat', 'Grains', ARRAY['Sucanat']),
('Muscovado', 'Grains', ARRAY['Muscovado sugar']),
('Turbinado', 'Grains', ARRAY['Turbinado sugar']),
('Demerara', 'Grains', ARRAY['Demerara sugar']),
('Palm Sugar', 'Grains', ARRAY['Palm sugar']),
('Coconut Sugar', 'Grains', ARRAY['Coconut sugar']),
('Date Sugar', 'Grains', ARRAY['Date sugar']),
('Maple Sugar', 'Grains', ARRAY['Maple sugar']),
('Stevia Extract', 'Grains', ARRAY['Stevia']),
('Monk Fruit', 'Grains', ARRAY['Monk fruit']),
('Erythritol', 'Grains', ARRAY['Erythritol']),
('Xylitol', 'Grains', ARRAY['Xylitol']),
('Agave Nectar', 'Grains', ARRAY['Agave nectar']),
('Fruit Juice Concentrate', 'Grains', ARRAY['Fruit juice concentrate']),
('Fondant', 'Grains', ARRAY['Fondant']),
('Marshmallow Fluff', 'Grains', ARRAY['Marshmallow fluff']),
('Marshmallows', 'Grains', ARRAY['Marshmallows']),
('Pectin', 'Grains', ARRAY['Pectin']),
('Gelatin', 'Grains', ARRAY['Gelatin']),
('Agar Agar', 'Grains', ARRAY['Agar agar']),
('Caramel', 'Grains', ARRAY['Caramel']),
('Butterscotch Chips', 'Grains', ARRAY['Butterscotch chips']),
('Toffee Bits', 'Grains', ARRAY['Toffee bits']),
('Marzipan', 'Grains', ARRAY['Marzipan']),
('Almond Paste', 'Grains', ARRAY['Almond paste']),
('Nutella', 'Grains', ARRAY['Nutella']),
('Dulce de Leche', 'Grains', ARRAY['Dulce de leche']),
-- Additional Condiments
('Ranch Dressing', 'Condiments', ARRAY['Ranch']),
('Caesar Dressing', 'Condiments', ARRAY['Caesar dressing']),
('Blue Cheese Dressing', 'Condiments', ARRAY['Blue cheese dressing']),
('Greek Dressing', 'Condiments', ARRAY['Greek dressing']),
('Vinaigrette', 'Condiments', ARRAY['Vinaigrette']),
('Sherry Vinegar', 'Condiments', ARRAY['Sherry vinegar']),
('Champagne Vinegar', 'Condiments', ARRAY['Champagne vinegar']),
('Red Wine Vinegar', 'Condiments', ARRAY['Red wine vinegar']),
('White Wine Vinegar', 'Condiments', ARRAY['White wine vinegar']),
('Apple Cider Vinegar', 'Condiments', ARRAY['Apple cider vinegar']),
('Malt Vinegar', 'Condiments', ARRAY['Malt vinegar']),
('Chinese Black Vinegar', 'Condiments', ARRAY['Black vinegar']),
('Seasoned Rice Vinegar', 'Condiments', ARRAY['Seasoned rice vinegar']),
('Mirin', 'Condiments', ARRAY['Mirin']),
('Sake', 'Condiments', ARRAY['Sake', 'Cooking sake']),
('Dashi Powder', 'Condiments', ARRAY['Dashi powder']),
('Mentsuyu', 'Condiments', ARRAY['Mentsuyu']),
('Ponzu', 'Condiments', ARRAY['Ponzu']),
('Yuzu Juice', 'Condiments', ARRAY['Yuzu juice']),
('Yuzu Kosho', 'Condiments', ARRAY['Yuzu kosho']),
('White Miso', 'Condiments', ARRAY['White miso']),
('Red Miso', 'Condiments', ARRAY['Red miso']),
('Barley Miso', 'Condiments', ARRAY['Barley miso']),
('Ssamjang', 'Condiments', ARRAY['Ssamjang']),
('Doenjang', 'Condiments', ARRAY['Doenjang']),
('Sesame Paste', 'Condiments', ARRAY['Sesame paste']),
('Chili Crisp', 'Condiments', ARRAY['Chili crisp']),
('Chili Oil', 'Condiments', ARRAY['Chili oil']),
('Sambal Oelek', 'Condiments', ARRAY['Sambal oelek']),
('Sriracha Mayo', 'Condiments', ARRAY['Sriracha mayo']),
('Spicy Mayo', 'Condiments', ARRAY['Spicy mayo']),
('Garlic Aioli', 'Condiments', ARRAY['Garlic aioli']),
('Chipotle Aioli', 'Condiments', ARRAY['Chipotle aioli']),
('Tartar Sauce', 'Condiments', ARRAY['Tartar sauce']),
('Cocktail Sauce', 'Condiments', ARRAY['Cocktail sauce']),
('Remoulade', 'Condiments', ARRAY['Remoulade']),
('Aioli', 'Condiments', ARRAY['Aioli']),
('Tapenade', 'Condiments', ARRAY['Tapenade']),
('Anchovy Paste', 'Condiments', ARRAY['Anchovy paste']),
('Garlic Paste', 'Condiments', ARRAY['Garlic paste']),
('Ginger Paste', 'Condiments', ARRAY['Ginger paste']),
('Roasted Red Pepper', 'Condiments', ARRAY['Roasted red peppers']),
('Piquillo Peppers', 'Condiments', ARRAY['Piquillo peppers']),
('Pepperoncini', 'Condiments', ARRAY['Pepperoncini']),
('Banana Pepper', 'Condiments', ARRAY['Banana peppers']),
('Harissa', 'Condiments', ARRAY['Harissa']),
('Zhug', 'Condiments', ARRAY['Zhug']),
('Shawarma Spice', 'Condiments', ARRAY['Shawarma spice']),
('Baharat', 'Condiments', ARRAY['Baharat']),
('Ras el Hanout', 'Condiments', ARRAY['Ras el hanout']),
('Dukkah', 'Condiments', ARRAY['Dukkah']),
('Berbere', 'Condiments', ARRAY['Berbere']),
('Piri Piri', 'Condiments', ARRAY['Piri piri']),
('Adobo', 'Condiments', ARRAY['Adobo']),
('Chimichurri', 'Condiments', ARRAY['Chimichurri']),
('Salsa Verde', 'Condiments', ARRAY['Salsa verde']),
('Salsa Roja', 'Condiments', ARRAY['Salsa roja']),
('Pico de Gallo', 'Condiments', ARRAY['Pico de gallo']),
('Mango Salsa', 'Condiments', ARRAY['Mango salsa']),
('Corn Salsa', 'Condiments', ARRAY['Corn salsa']),
('Marinara Sauce', 'Condiments', ARRAY['Marinara sauce']),
('Alfredo Sauce', 'Condiments', ARRAY['Alfredo sauce']),
('Vodka Sauce', 'Condiments', ARRAY['Vodka sauce']),
('Bolognese Sauce', 'Condiments', ARRAY['Bolognese']),
('Pizza Sauce', 'Condiments', ARRAY['Pizza sauce']),
('Buffalo Sauce', 'Condiments', ARRAY['Buffalo sauce']),
('Sweet and Sour Sauce', 'Condiments', ARRAY['Sweet and sour sauce']),
('Plum Sauce', 'Condiments', ARRAY['Plum sauce']),
('Duck Sauce', 'Condiments', ARRAY['Duck sauce']),
('General Tso Sauce', 'Condiments', ARRAY['General Tso sauce']),
('Kung Pao Sauce', 'Condiments', ARRAY['Kung pao sauce']),
('XO Sauce', 'Condiments', ARRAY['XO sauce']),
('Tom Yum Paste', 'Condiments', ARRAY['Tom yum paste']),
('Green Curry Paste', 'Condiments', ARRAY['Green curry paste']),
('Red Curry Paste', 'Condiments', ARRAY['Red curry paste']),
('Yellow Curry Paste', 'Condiments', ARRAY['Yellow curry paste']),
('Massaman Curry Paste', 'Condiments', ARRAY['Massaman curry paste']),
('Laksa Paste', 'Condiments', ARRAY['Laksa paste']),
('Sambar Powder', 'Condiments', ARRAY['Sambar powder']),
('Garam Masala Powder', 'Condiments', ARRAY['Garam masala']),
('Tandoori Masala', 'Condiments', ARRAY['Tandoori masala']),
-- Additional Baking
('Dutch Process Cocoa', 'Baking', ARRAY['Dutch cocoa']),
('Natural Cocoa', 'Baking', ARRAY['Natural cocoa']),
('Cocoa Butter', 'Baking', ARRAY['Cocoa butter']),
('Cocoa Nibs', 'Baking', ARRAY['Cocoa nibs']),
('Dark Chocolate', 'Baking', ARRAY['Dark chocolate']),
('Milk Chocolate', 'Baking', ARRAY['Milk chocolate']),
('White Chocolate', 'Baking', ARRAY['White chocolate']),
('Unsweetened Chocolate', 'Baking', ARRAY['Unsweetened chocolate']),
('Bittersweet Chocolate', 'Baking', ARRAY['Bittersweet chocolate']),
('Semisweet Chocolate', 'Baking', ARRAY['Semisweet chocolate']),
('Couverture Chocolate', 'Baking', ARRAY['Couverture chocolate']),
('Chocolate Melting Wafers', 'Baking', ARRAY['Chocolate melting wafers']),
('Candy Melts', 'Baking', ARRAY['Candy melts']),
-- Additional Snacks
('Potato Chips', 'Snacks', ARRAY['Potato chips', 'Chips']),
('Tortilla Chips', 'Snacks', ARRAY['Tortilla chips']),
('Pretzels', 'Snacks', ARRAY['Pretzels']),
('Popcorn', 'Snacks', ARRAY['Popcorn', 'Popcorn kernels']),
('Trail Mix', 'Snacks', ARRAY['Trail mix']),
('Mixed Nuts', 'Snacks', ARRAY['Mixed nuts']),
('Roasted Almonds', 'Snacks', ARRAY['Roasted almonds']),
('Roasted Cashews', 'Snacks', ARRAY['Roasted cashews']),
('Pistachios', 'Snacks', ARRAY['Pistachios']),
('Dried Mango', 'Snacks', ARRAY['Dried mango']),
('Dried Apricots', 'Snacks', ARRAY['Dried apricots']),
('Dried Cranberries', 'Snacks', ARRAY['Dried cranberries']),
('Dried Blueberries', 'Snacks', ARRAY['Dried blueberries']),
('Apple Chips', 'Snacks', ARRAY['Apple chips']),
('Banana Chips', 'Snacks', ARRAY['Banana chips']),
('Beef Jerky', 'Snacks', ARRAY['Beef jerky']),
('Seaweed Snacks', 'Snacks', ARRAY['Seaweed snacks']),
('Edamame', 'Snacks', ARRAY['Edamame']),
('Rice Cakes', 'Snacks', ARRAY['Rice cakes']),
('Granola Bars', 'Snacks', ARRAY['Granola bars']),
('Protein Bars', 'Snacks', ARRAY['Protein bars']),
('Cheese Crackers', 'Snacks', ARRAY['Cheese crackers']),
('Graham Crackers', 'Snacks', ARRAY['Graham crackers']),
-- Additional Beverages
('Coffee Beans', 'Beverages', ARRAY['Coffee beans']),
('Ground Coffee', 'Beverages', ARRAY['Ground coffee']),
('Espresso Powder', 'Beverages', ARRAY['Espresso powder']),
('Instant Coffee', 'Beverages', ARRAY['Instant coffee']),
('Green Tea', 'Beverages', ARRAY['Green tea']),
('Black Tea', 'Beverages', ARRAY['Black tea']),
('Oolong Tea', 'Beverages', ARRAY['Oolong tea']),
('White Tea', 'Beverages', ARRAY['White tea']),
('Herbal Tea', 'Beverages', ARRAY['Herbal tea']),
('Chai Tea', 'Beverages', ARRAY['Chai tea']),
('Matcha', 'Beverages', ARRAY['Matcha']),
('Earl Grey', 'Beverages', ARRAY['Earl Grey']),
('Rooibos', 'Beverages', ARRAY['Rooibos']),
('Orange Juice', 'Beverages', ARRAY['Orange juice']),
('Apple Juice', 'Beverages', ARRAY['Apple juice']),
('Cranberry Juice', 'Beverages', ARRAY['Cranberry juice']),
('Grape Juice', 'Beverages', ARRAY['Grape juice']),
('Pineapple Juice', 'Beverages', ARRAY['Pineapple juice']),
('Tomato Juice', 'Beverages', ARRAY['Tomato juice']),
('Lemonade', 'Beverages', ARRAY['Lemonade']),
('Sparkling Water', 'Beverages', ARRAY['Sparkling water']),
('Tonic Water', 'Beverages', ARRAY['Tonic water']),
('Club Soda', 'Beverages', ARRAY['Club soda']),
('Energy Drink', 'Beverages', ARRAY['Energy drink']),
('Sports Drink', 'Beverages', ARRAY['Sports drink']),
('Coconut Water', 'Beverages', ARRAY['Coconut water']),
('Kombucha', 'Beverages', ARRAY['Kombucha']),
('Kefir', 'Beverages', ARRAY['Kefir']),
('Protein Shake', 'Beverages', ARRAY['Protein shake']),
-- Additional Frozen
('Frozen Berries', 'Frozen', ARRAY['Frozen berries']),
('Frozen Mango', 'Frozen', ARRAY['Frozen mango']),
('Frozen Pineapple', 'Frozen', ARRAY['Frozen pineapple']),
('Frozen Spinach', 'Frozen', ARRAY['Frozen spinach']),
('Frozen Broccoli', 'Frozen', ARRAY['Frozen broccoli']),
('Frozen Mixed Vegetables', 'Frozen', ARRAY['Frozen mixed vegetables']),
('Frozen French Fries', 'Frozen', ARRAY['Frozen french fries']),
('Frozen Tater Tots', 'Frozen', ARRAY['Frozen tater tots']),
('Frozen Dumplings', 'Frozen', ARRAY['Frozen dumplings']),
('Frozen Egg Rolls', 'Frozen', ARRAY['Frozen egg rolls']),
('Frozen Potstickers', 'Frozen', ARRAY['Frozen potstickers']),
('Frozen Falafel', 'Frozen', ARRAY['Frozen falafel']),
('Frozen Fish Sticks', 'Frozen', ARRAY['Frozen fish sticks']),
('Frozen Chicken Nuggets', 'Frozen', ARRAY['Frozen chicken nuggets']),
('Frozen Chicken Wings', 'Frozen', ARRAY['Frozen chicken wings']),
('Frozen Hamburgers', 'Frozen', ARRAY['Frozen hamburgers']),
('Frozen Hot Dogs', 'Frozen', ARRAY['Frozen hot dogs']),
('Frozen Burritos', 'Frozen', ARRAY['Frozen burritos']),
('Frozen Chimichangas', 'Frozen', ARRAY['Frozen chimichangas']),
('Frozen Lasagna', 'Frozen', ARRAY['Frozen lasagna']),
('Frozen Mac and Cheese', 'Frozen', ARRAY['Frozen mac and cheese']),
('Frozen Soup', 'Frozen', ARRAY['Frozen soup']),
('Frozen Bread Dough', 'Frozen', ARRAY['Frozen bread dough']),
('Frozen Croissants', 'Frozen', ARRAY['Frozen croissants']),
('Frozen Puff Pastry', 'Frozen', ARRAY['Frozen puff pastry']),
('Frozen Pie Crust', 'Frozen', ARRAY['Frozen pie crust']),
('Sorbet', 'Frozen', ARRAY['Sorbet']),
('Sherbet', 'Frozen', ARRAY['Sherbet']),
('Frozen Yogurt', 'Frozen', ARRAY['Frozen yogurt']),
('Gelato', 'Frozen', ARRAY['Gelato']);

