-- Seed file with additional ingredients (Migration 3)
-- Run this after seed-ingredients.sql and seed-ingredients2.sql
-- Uses ON CONFLICT DO NOTHING to avoid duplicates
-- Total new ingredients: ~200

-- More Asian Ingredients
INSERT INTO ingredients (name, category, aliases) VALUES
('Bean Sprouts', 'Produce', ARRAY['Bean sprouts', 'Mung bean sprouts']),
('Snow Peas', 'Produce', ARRAY['Snow peas', 'Mange tout']),
('Sugar Snap Peas', 'Produce', ARRAY['Sugar snap peas']),
('Baby Corn', 'Produce', ARRAY['Baby corn']),
('Water Chestnuts', 'Produce', ARRAY['Water chestnuts']),
('Bamboo Shoots', 'Produce', ARRAY['Bamboo shoots']),
('Chinese Broccoli', 'Produce', ARRAY['Chinese broccoli', 'Gai lan']),
('Bok Choy', 'Produce', ARRAY['Bok choy', 'Pak choi']),
('Baby Bok Choy', 'Produce', ARRAY['Baby bok choy']),
('Shanghai Bok Choy', 'Produce', ARRAY['Shanghai bok choy']),
('Choy Sum', 'Produce', ARRAY['Choy sum']),
('Yu Choy', 'Produce', ARRAY['Yu choy']),
('Water Spinach', 'Produce', ARRAY['Water spinach', 'Morning glory']),
('Chinese Eggplant', 'Produce', ARRAY['Chinese eggplant']),
('Thai Eggplant', 'Produce', ARRAY['Thai eggplant']),
('Japanese Cucumber', 'Produce', ARRAY['Japanese cucumber', 'Kyuri']),
('Korean Pear', 'Produce', ARRAY['Korean pear', 'Asian pear']),
('Asian Pear', 'Produce', ARRAY['Asian pear']),
('Chinese Sausage', 'Meat', ARRAY['Chinese sausage', 'Lap cheong']),
('Vinegar', 'Condiments', ARRAY['Vinegar']),
('Black Vinegar', 'Condiments', ARRAY['Black vinegar', 'Chinkiang vinegar']),
('Light Soy Sauce', 'Condiments', ARRAY['Light soy sauce']),
('Dark Soy Sauce', 'Condiments', ARRAY['Dark soy sauce']),
('Thick Soy Sauce', 'Condiments', ARRAY['Thick soy sauce']),
('Fermented Black Beans', 'Condiments', ARRAY['Fermented black beans', 'Douchi']),
('Fermented Soy Sauce', 'Condiments', ARRAY['Fermented soy sauce']),
('Soy Bean Paste', 'Condiments', ARRAY['Soy bean paste']),
('Tao Bai', 'Condiments', ARRAY['Tao bai']),
('Shrimp Paste', 'Condiments', ARRAY['Shrimp paste']),
('Belachan', 'Condiments', ARRAY['Belachan', 'Shrimp paste']),
('Coconut Aminos', 'Condiments', ARRAY['Coconut aminos']),
('Tamarind Water', 'Condiments', ARRAY['Tamarind water']),
('Lime Juice', 'Produce', ARRAY['Lime juice']),
('Lemon Juice', 'Produce', ARRAY['Lemon juice']),
('Makrut Lime', 'Produce', ARRAY['Makrut lime', 'Kaffir lime']),
('Fingerroot', 'Produce', ARRAY['Fingerroot', 'Boesenbergia']),
('Cantonese Ginger', 'Produce', ARRAY['Cantonese ginger']),
('Thai Ginger', 'Produce', ARRAY['Thai ginger']),
('Mango Ginger', 'Produce', ARRAY['Mango ginger']),
('Zhebei', 'Produce', ARRAY['Zhebei', 'Chinese chives']),
('Garlic Chives', 'Produce', ARRAY['Garlic chives', 'Chinese chives']),
('Chinese Onion', 'Produce', ARRAY['Chinese onion', 'Scallions']),
('Thai Chile', 'Produce', ARRAY['Thai chile', 'Bird chile']),
('Bird Eye Chile', 'Produce', ARRAY['Bird eye chile']),
('Scotch Bonnet', 'Produce', ARRAY['Scotch bonnet']),
('Habanero', 'Produce', ARRAY['Habanero']),
('Serrano', 'Produce', ARRAY['Serrano']),
(' Fresno Chile', 'Produce', ARRAY['Fresno chile']),
('Poblano', 'Produce', ARRAY['Poblano']),
('Anaheim', 'Produce', ARRAY['Anaheim']),
('Cubanelle', 'Produce', ARRAY['Cubanelle']),
('Shishito', 'Produce', ARRAY['Shishito']),
('Padron', 'Produce', ARRAY['Padron']),
('Thai Rau Ram', 'Produce', ARRAY['Rau ram', 'Vietnamese coriander']),
('Perilla', 'Produce', ARRAY['Perilla', 'Shiso']),
('Vietnamese Coriander', 'Produce', ARRAY['Vietnamese coriander']),
('Coconut', 'Produce', ARRAY['Coconut']),
('Coconut Meat', 'Produce', ARRAY['Coconut meat']),
('Coconut Water', 'Beverages', ARRAY['Coconut water'])
ON CONFLICT (name) DO NOTHING;

-- More Indian Ingredients
INSERT INTO ingredients (name, category, aliases) VALUES
('Tamarind Chutney', 'Condiments', ARRAY['Tamarind chutney']),
('Mint Chutney', 'Condiments', ARRAY['Mint chutney']),
('Coconut Chutney', 'Condiments', ARRAY['Coconut chutney']),
('Coriander Chutney', 'Condiments', ARRAY['Coriander chutney']),
('Garlic Chutney', 'Condiments', ARRAY['Garlic chutney']),
('Amla', 'Produce', ARRAY['Amla', 'Indian gooseberry']),
('Raw Mango', 'Produce', ARRAY['Raw mango', 'Keri']),
('Kokum', 'Produce', ARRAY['Kokum']),
('Gunda', 'Produce', ARRAY['Gunda']),
('Gur', 'Grains', ARRAY['Gur', 'Jaggery']),
('Palm Jaggery', 'Grains', ARRAY['Palm jaggery']),
('Khandela', 'Condiments', ARRAY['Khandela']),
('Ajwain', 'Produce', ARRAY['Ajwain', 'Carom']),
('Black Salt', 'Produce', ARRAY['Black salt', 'Kala namak']),
('Gingelly Oil', 'Condiments', ARRAY['Gingelly oil', 'Sesame oil']),
('Groundnut Oil', 'Condiments', ARRAY['Groundnut oil', 'Peanut oil']),
('Sunflower Oil', 'Condiments', ARRAY['Sunflower oil']),
('Rice Bran Oil', 'Condiments', ARRAY['Rice bran oil']),
('Tadka', 'Condiments', ARRAY['Tadka', 'Tempering']),
('Baghaar', 'Condiments', ARRAY['Baghaar']),
('Bhunao', 'Condiments', ARRAY['Bhunao']),
('Kashmiri Tea', 'Beverages', ARRAY['Kashmiri tea', 'Noon chai'])
ON CONFLICT (name) DO NOTHING;

-- More Mexican/Latin Ingredients
INSERT INTO ingredients (name, category, aliases) VALUES
('Huitlacoche', 'Produce', ARRAY['Huitlacoche', 'Corn mushroom']),
('Chapulines', 'Snacks', ARRAY['Chapulines', 'Grasshoppers']),
('Escamoles', 'Produce', ARRAY['Escamoles', 'Ant eggs']),
('Aguachile', 'Condiments', ARRAY['Aguachile']),
('Adobo Seasoning', 'Condiments', ARRAY['Adobo seasoning']),
('Recado Rojo', 'Condiments', ARRAY['Recado rojo']),
('Recado Negro', 'Condiments', ARRAY['Recado negro']),
('Achiote', 'Condiments', ARRAY['Achiote', 'Annatto']),
('Annatto', 'Condiments', ARRAY['Annatto', 'Achiote']),
('Sazon', 'Condiments', ARRAY['Sazon']),
('Comino', 'Produce', ARRAY['Comino', 'Cumin']),
('Hoja de Aguacate', 'Produce', ARRAY['Hoja de aguacate']),
('Aguacate', 'Produce', ARRAY['Aguacate', 'Avocado']),
('Chicharron', 'Snacks', ARRAY['Chicharron']),
('Chicharrones', 'Snacks', ARRAY['Chicharrones']),
('Tostada', 'Produce', ARRAY['Tostada']),
('Tostadas', 'Produce', ARRAY['Tostadas']),
('Totopo', 'Produce', ARRAY['Totopo']),
('Bolillo', 'Grains', ARRAY['Bolillo']),
('Telera', 'Grains', ARRAY['Telera']),
('Baguette', 'Grains', ARRAY['Baguette']),
('Manteca', 'Dairy', ARRAY['Manteca', 'Lard']),
('Manteca de Cerdo', 'Dairy', ARRAY['Manteca de cerdo']),
('Achiote Paste', 'Condiments', ARRAY['Achiote paste']),
('Rajas', 'Produce', ARRAY['Rajas']),
('Chiles Rellenos', 'Produce', ARRAY['Chiles rellenos']),
('Calabacita', 'Produce', ARRAY['Calabacita']),
('Chayote Squash', 'Produce', ARRAY['Chayote']),
('Xoconostle', 'Produce', ARRAY['Xoconostle']),
('Tuna', 'Produce', ARRAY['Tuna', 'Prickly pear']),
('Nopal', 'Produce', ARRAY['Nopal']),
('Romero', 'Produce', ARRAY['Romero', 'Rosemary']),
('Hierbabuena', 'Produce', ARRAY['Hierbabuena', 'Mint']),
('Ajenjo', 'Produce', ARRAY['Ajenjo', 'Wormwood']),
('Pitiona', 'Produce', ARRAY['Pitiona']),
('Chocolate Abocado', 'Baking', ARRAY['Chocolate abocado']),
('Tejate', 'Beverages', ARRAY['Tejate']),
('Atole Blanco', 'Grains', ARRAY['Atole blanco']),
('Atole Rojo', 'Grains', ARRAY['Atole rojo']),
('Pinole', 'Grains', ARRAY['Pinole'])
ON CONFLICT (name) DO NOTHING;

-- More Mediterranean/Middle Eastern
INSERT INTO ingredients (name, category, aliases) VALUES
('Lamb Ribs', 'Meat', ARRAY['Lamb ribs']),
('Lamb Feet', 'Meat', ARRAY['Lamb feet']),
('Lamb Head', 'Meat', ARRAY['Lamb head']),
('Beef Shank', 'Meat', ARRAY['Beef shank']),
('Beef Cheek', 'Meat', ARRAY['Beef cheek']),
('Beef Belly', 'Meat', ARRAY['Beef belly']),
('Veal', 'Meat', ARRAY['Veal']),
('Veal Chop', 'Meat', ARRAY['Veal chop']),
('Veal Shank', 'Meat', ARRAY['Veal shank', 'Osso buco']),
('Chicken Leg', 'Meat', ARRAY['Chicken leg']),
('Whole Chicken', 'Meat', ARRAY['Whole chicken']),
('Capon', 'Meat', ARRAY['Capon']),
('Squab', 'Meat', ARRAY['Squab']),
('Woodcock', 'Meat', ARRAY['Woodcock']),
('Snipe', 'Meat', ARRAY['Snipe']),
('Muscovy Duck', 'Meat', ARRAY['Muscovy duck']),
('Guinea Fowl', 'Meat', ARRAY['Guinea fowl']),
('Ostrich', 'Meat', ARRAY['Ostrich']),
('Emu', 'Meat', ARRAY['Emu']),
('Shark', 'Seafood', ARRAY['Shark']),
('Stingray', 'Seafood', ARRAY['Stingray']),
('Monkfish', 'Seafood', ARRAY['Monkfish']),
('Anglerfish', 'Seafood', ARRAY['Anglerfish']),
('Gefilte Fish', 'Seafood', ARRAY['Gefilte fish']),
('Matjes Herring', 'Seafood', ARRAY['Matjes herring']),
('Rollmops', 'Seafood', ARRAY['Rollmops']),
('Fenkous', 'Seafood', ARRAY['Fenkous']),
('Sardine Paste', 'Condiments', ARRAY['Sardine paste']),
('Anchovy Essence', 'Condiments', ARRAY['Anchovy essence']),
('Worcestershire Sauce', 'Condiments', ARRAY['Worcestershire sauce']),
('Maggi', 'Condiments', ARRAY['Maggi']),
('Aromat', 'Condiments', ARRAY['Aromat']),
('Stock Cube', 'Condiments', ARRAY['Stock cube']),
('Bouillon Cube', 'Condiments', ARRAY['Bouillon cube']),
('Chicken Cube', 'Condiments', ARRAY['Chicken cube']),
('Beef Cube', 'Condiments', ARRAY['Beef cube']),
('Vegetable Cube', 'Condiments', ARRAY['Vegetable cube']),
('Knorr', 'Condiments', ARRAY['Knorr']),
('Marmite', 'Condiments', ARRAY['Marmite']),
('Vegemite', 'Condiments', ARRAY['Vegemite']),
('Cecina', 'Meat', ARRAY['Cecina']),
('Soppressata', 'Meat', ARRAY['Soppressata']),
('Coppa', 'Meat', ARRAY['Coppa']),
('Bresaola', 'Meat', ARRAY['Bresaola']),
('Lomo', 'Meat', ARRAY['Lomo']),
('Filetto', 'Meat', ARRAY['Filetto']),
('Nduja', 'Condiments', ARRAY['Nduja'])
ON CONFLICT (name) DO NOTHING;

-- More Herbs, Spices & Flavorings
INSERT INTO ingredients (name, category, aliases) VALUES
('Lovage', 'Produce', ARRAY['Lovage']),
('Burnet', 'Produce', ARRAY['Burnet']),
('Stevia', 'Produce', ARRAY['Stevia']),
('Yarrow', 'Produce', ARRAY['Yarrow']),
('Hyssop', 'Produce', ARRAY['Hyssop']),
('Savory', 'Produce', ARRAY['Savory']),
('Winter Savory', 'Produce', ARRAY['Winter savory']),
('Summer Savory', 'Produce', ARRAY['Summer savory']),
('Horehound', 'Produce', ARRAY['Horehound']),
('Marrubium', 'Produce', ARRAY['Marrubium']),
('Bergamot', 'Produce', ARRAY['Bergamot']),
('Monarda', 'Produce', ARRAY['Monarda']),
('Bee Balm', 'Produce', ARRAY['Bee balm']),
('Calendum', 'Produce', ARRAY['Calendum']),
('Coriander Leaf', 'Produce', ARRAY['Coriander leaf']),
('Celery Leaf', 'Produce', ARRAY['Celery leaf']),
('Dill Leaf', 'Produce', ARRAY['Dill leaf']),
('Fennel Leaf', 'Produce', ARRAY['Fennel leaf']),
('Tarragon Leaf', 'Produce', ARRAY['Tarragon leaf']),
('Lime Leaf', 'Produce', ARRAY['Lime Leaf']),
('Curry Leaf', 'Produce', ARRAY['Curry Leaf']),
('Citrus Leaf', 'Produce', ARRAY['Citrus leaf']),
('Myrtle', 'Produce', ARRAY['Myrtle']),
('Sassafras', 'Produce', ARRAY['Sassafras']),
('Sarsaparilla', 'Produce', ARRAY['Sarsaparilla']),
('Ginseng', 'Produce', ARRAY['Ginseng']),
('Mace', 'Produce', ARRAY['Mace']),
('Grains of Paradise', 'Produce', ARRAY['Grains of paradise']),
('Melegueta Pepper', 'Produce', ARRAY['Melegueta pepper']),
('Alligator Pepper', 'Produce', ARRAY['Alligator pepper']),
('Paradise Pepper', 'Produce', ARRAY['Paradise pepper']),
('Long Pepper', 'Produce', ARRAY['Long pepper']),
('Pippali', 'Produce', ARRAY['Pippali']),
('Cubeb', 'Produce', ARRAY['Cubeb']),
('Tasmanian Pepper', 'Produce', ARRAY['Tasmanian pepper']),
('Pepperberry', 'Produce', ARRAY['Pepperberry']),
('Hill Pepper', 'Produce', ARRAY['Hill pepper']),
('Rongho', 'Produce', ARRAY['Rongho']),
('Urfa Biber', 'Produce', ARRAY['Urfa biber']),
('Aleppo Pepper', 'Produce', ARRAY['Aleppo pepper']),
('Marash Pepper', 'Produce', ARRAY['Marash pepper']),
('Pul Biber', 'Produce', ARRAY['Pul biber']),
('Choclot', 'Produce', ARRAY['Choclot']),
('Alevante', 'Produce', ARRAY['Alevante']),
('Mahlab', 'Produce', ARRAY['Mahlab']),
('Mahleb', 'Produce', ARRAY['Mahleb']),
('Sweet Laurel', 'Produce', ARRAY['Sweet laurel']),
('Bay Rum', 'Condiments', ARRAY['Bay rum']),
('Attar of Roses', 'Condiments', ARRAY['Attar of roses']),
('Rose Essence', 'Condiments', ARRAY['Rose essence']),
('Orange Blossom Essence', 'Condiments', ARRAY['Orange blossom essence']),
('Neroli', 'Condiments', ARRAY['Neroli'])
ON CONFLICT (name) DO NOTHING;

-- More Specialty/Unique Items
INSERT INTO ingredients (name, category, aliases) VALUES
('Caviar', 'Seafood', ARRAY['Caviar']),
('Beluga Caviar', 'Seafood', ARRAY['Beluga caviar']),
('Osetra Caviar', 'Seafood', ARRAY['Osetra caviar']),
('Sevruga Caviar', 'Seafood', ARRAY['Sevruga caviar']),
('Hackleback Caviar', 'Seafood', ARRAY['Hackleback caviar']),
('Paddlefish Caviar', 'Seafood', ARRAY['Paddlefish caviar']),
('Sterlet Caviar', 'Seafood', ARRAY['Sterlet caviar']),
('Salmon Caviar', 'Seafood', ARRAY['Salmon caviar']),
('White Sturgeon Caviar', 'Seafood', ARRAY['White sturgeon caviar']),
('Foie Gras', 'Meat', ARRAY['Foie gras']),
('Duck Foie Gras', 'Meat', ARRAY['Duck foie gras']),
('Goose Foie Gras', 'Meat', ARRAY['Goose foie gras']),
(' Wagyu', 'Meat', ARRAY['Wagyu']),
('Kobe Beef', 'Meat', ARRAY['Kobe beef']),
('Matsusaka Beef', 'Meat', ARRAY['Matsusaka beef']),
('Hida Gyu', 'Meat', ARRAY['Hida gyu']),
('Ohmi Beef', 'Meat', ARRAY['Ohmi beef']),
('Black Angus', 'Meat', ARRAY['Black angus']),
('Prime Rib', 'Meat', ARRAY['Prime rib']),
('Porterhouse', 'Meat', ARRAY['Porterhouse']),
('T-Bone', 'Meat', ARRAY['T-bone']),
('Tomahawk', 'Meat', ARRAY['Tomahawk']),
('Cote de Boeuf', 'Meat', ARRAY['Cote de boeuf']),
('Chateaubriand', 'Meat', ARRAY['Chateaubriand']),
('Filet Mignon', 'Meat', ARRAY['Filet mignon']),
('Ribeye', 'Meat', ARRAY['Ribeye']),
('New York Strip', 'Meat', ARRAY['New york strip']),
('Flank Steak', 'Meat', ARRAY['Flank steak']),
('Skirt Steak', 'Meat', ARRAY['Skirt steak']),
('Flat Iron Steak', 'Meat', ARRAY['Flat iron steak']),
('Hanger Steak', 'Meat', ARRAY['Hanger steak']),
('Merquez', 'Meat', ARRAY['Merquez']),
('Merguez', 'Meat', ARRAY['Merguez']),
('Boudin', 'Meat', ARRAY['Boudin']),
('Boudin Blanc', 'Meat', ARRAY['Boudin blanc']),
('Boudin Noir', 'Meat', ARRAY['Boudin noir']),
('Andouille', 'Meat', ARRAY['Andouille']),
('Cervellati', 'Meat', ARRAY['Cervellati']),
('Finocchiona', 'Meat', ARRAY['Finocchiona']),
('Guanciale', 'Meat', ARRAY['Guanciale']),
('Lardo', 'Meat', ARRAY['Lardo']),
('Strutto', 'Dairy', ARRAY['Strutto']),
('Lardo di Arnad', 'Meat', ARRAY['Lardo di Arnad']),
('Nduja Calabrese', 'Meat', ARRAY['Nduja calabrese']),
('Salami Calabrese', 'Meat', ARRAY['Salami calabrese']),
('Soppressata Calabrese', 'Meat', ARRAY['Soppressata calabrese']),
('Coppa Calabrese', 'Meat', ARRAY['Coppa calabrese'])
ON CONFLICT (name) DO NOTHING;
